import { readFile } from 'node:fs/promises'
import { test, expect } from './fixtures.js'
import { createSpace, register, signIn } from './helpers.js'

test('two Apps publish independent manifests, retain private content and remove only their own registrations', async ({ page, browser, environment }, testInfo) => {
  test.setTimeout(120_000)
  const user = await register(page, 'PWA owner')
  await signIn(page, user)
  const space = await createSpace(page, 'Private files', undefined, 'note')
  const api = `/api/namespaces/${space.account}/spaces/${space.slug}`
  const { id } = await (await page.request.get(api)).json() as { id: string }
  const second = await (await page.request.post(api + '/apps', { data: { appType: 'note', name: 'Second' } })).json() as { id: string }
  const upload = await page.request.put(api + '/objects/Secret.md', { data: '# Private words', headers: { 'content-type': 'text/markdown' } })
  expect(upload.status()).toBe(201)
  const note = await upload.json() as { id: string }
  expect((await page.request.put(api + '/objects/icons/photo.png', { data: await readFile(new URL('./media-fixtures/photo.png', import.meta.url)), headers: { 'content-type': 'image/png' } })).status()).toBe(201)
  const firstPath = `/app/note/${id}/`
  const secondPath = `/app/note/${second.id}/`
  expect(await (await page.request.get(firstPath)).text()).not.toContain('rel="manifest"')
  await page.getByRole('link', { name: 'Installation settings', exact: true }).click()
  const panel = page.getByRole('region', { name: 'Space apps' })
  await panel.getByRole('button', { name: 'PWA settings for Private files' }).click()
  const dialog = page.getByRole('dialog', { name: 'PWA settings', exact: true })
  await dialog.getByLabel('Enable PWA', { exact: true }).check()
  await dialog.getByLabel('App and installation name', { exact: true }).fill('Published notebook')
  await dialog.getByLabel('Installation icon', { exact: true }).selectOption('file')
  await dialog.getByLabel('Icon file path', { exact: true }).fill('icons/photo.png')
  await dialog.getByLabel('Theme color', { exact: true }).fill('#224466')
  await expect(dialog.getByRole('button', { name: 'Save PWA settings' })).toBeDisabled()
  await dialog.getByLabel(/I understand that the app name/).check()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('pwa-settings-mobile.png'), animations: 'disabled' })
  await dialog.getByRole('button', { name: 'Save PWA settings' }).click()
  await expect(dialog).not.toBeVisible()
  await expect(panel.getByRole('status')).toContainText('Installation metadata is public')
  await panel.getByRole('button', { name: 'PWA settings for Second' }).click()
  await dialog.getByLabel('Enable PWA', { exact: true }).check()
  await dialog.getByLabel(/I understand that the app name/).check()
  await dialog.getByRole('button', { name: 'Save PWA settings' }).click()
  await expect(dialog).not.toBeVisible()
  const firstManifest = await (await page.request.get(firstPath + 'manifest.webmanifest')).json() as { id: string; name: string; scope: string; icons: { src: string }[] }
  const secondManifest = await (await page.request.get(secondPath + 'manifest.webmanifest')).json() as typeof firstManifest
  expect(firstManifest.id).not.toBe(secondManifest.id)
  expect(firstManifest.scope).toBe(firstPath)
  expect(secondManifest.scope).toBe(secondPath)
  expect(firstManifest.name).toBe('Published notebook')
  const firstApp = await page.context().newPage()
  const firstResponse = await firstApp.goto(firstPath + 'note/' + note.id)
  expect(await firstResponse!.text()).toContain(`href="${firstPath}manifest.webmanifest"`)
  await expect(firstApp.getByRole('textbox', { name: 'Note content', exact: true })).toContainText('Private words')
  await expect(firstApp.locator('link[rel="manifest"]')).toHaveAttribute('href', firstPath + 'manifest.webmanifest')
  await firstApp.reload()
  await expect(firstApp).toHaveTitle('Published notebook · Note')
  const secondApp = await page.context().newPage()
  await secondApp.goto(secondPath)
  await expect(secondApp.getByRole('link', { name: 'Open Secret.md' })).toBeVisible()
  const scopes = [environment.webOrigin + firstPath, environment.webOrigin + secondPath].sort()
  await expect.poll(() => firstApp.evaluate(async () => (await navigator.serviceWorker.getRegistrations()).filter(registration => registration.active).map(registration => registration.scope).sort())).toEqual(scopes)
  expect(await firstApp.evaluate(async () => Boolean(await navigator.serviceWorker.getRegistration(location.origin + '/')))).toBe(false)
  expect(await firstApp.evaluate(() => caches.keys())).toEqual([])
  const guestContext = await browser.newContext()
  try {
    const guest = await guestContext.newPage()
    const deep = environment.webOrigin + firstPath + 'note/' + note.id + '?search=Secret'
    await guest.goto(deep)
    await expect(guest.getByRole('heading', { name: 'Sign in to open this app' })).toBeVisible()
    await expect(guest.locator('link[rel="manifest"]')).toHaveAttribute('href', firstPath + 'manifest.webmanifest')
    expect((await guest.request.get(environment.webOrigin + firstManifest.icons[0]!.src)).status()).toBe(200)
    expect((await guest.request.get(environment.webOrigin + api + '/objects/Secret.md')).status()).toBe(401)
    await guest.getByRole('link', { name: 'Sign in', exact: true }).click()
    await expect(guest.locator('link[rel="manifest"]')).toHaveCount(0)
    await guest.getByLabel('Email', { exact: true }).fill(user.email)
    await guest.getByLabel('Password', { exact: true }).fill(user.password)
    await guest.getByRole('main').getByRole('button', { name: 'Sign in', exact: true }).click()
    await expect(guest).toHaveURL(deep)
    await expect(guest.getByRole('textbox', { name: 'Note content', exact: true })).toContainText('Private words')
  } finally { await guestContext.close() }

  await page.request.patch(api + '/apps/' + id, { data: { name: 'Renamed notebook' } })
  expect((await (await page.request.get(firstPath + 'manifest.webmanifest')).json()).id).toBe(firstManifest.id)
  await page.reload()
  await panel.getByRole('button', { name: 'PWA settings for Renamed notebook' }).click()
  await dialog.getByLabel('Enable PWA', { exact: true }).uncheck()
  await dialog.getByRole('button', { name: 'Save PWA settings' }).click()
  await expect(dialog).not.toBeVisible()
  await firstApp.reload()
  await expect(firstApp.getByRole('textbox', { name: 'Note content', exact: true })).toContainText('Private words')
  await expect(firstApp.locator('link[rel="manifest"]')).toHaveCount(0)
  await expect.poll(() => firstApp.evaluate(async () => (await navigator.serviceWorker.getRegistrations()).map(registration => registration.scope))).toEqual([environment.webOrigin + secondPath])
  expect((await page.request.get(firstPath + 'manifest.webmanifest')).status()).toBe(404)
  expect((await page.request.get(firstPath + 'icon-192.png')).status()).toBe(404)
  expect((await page.request.get(secondPath + 'manifest.webmanifest')).status()).toBe(200)
  await page.request.delete(api + '/apps/' + second.id)
  await secondApp.bringToFront()
  await secondApp.evaluate(() => window.dispatchEvent(new Event('visibilitychange')))
  // Refetch failures retain stale query data; a 404 must still remove metadata.
  await expect(secondApp.getByRole('heading', { name: 'App not found' })).toBeVisible({ timeout: 40_000 })
  await expect(secondApp.locator('link[rel="manifest"]')).toHaveCount(0)
  await expect.poll(() => secondApp.evaluate(async () => (await navigator.serviceWorker.getRegistrations()).length)).toBe(0)
  for (const resource of ['sw.js', 'manifest.webmanifest', 'icon-192.png']) {
    const response = await page.request.get(secondPath + resource)
    expect(response.status()).toBe(404)
    expect(response.headers()['content-type']).not.toContain('text/html')
  }
  expect(await (await page.request.get(api + '/objects/Secret.md')).text()).toBe('# Private words')
  await firstApp.close(); await secondApp.close()
})

test('PWA settings retain failed drafts and reject a revoked owner before publishing', async ({ page, environment }, testInfo) => {
  const user = await register(page, 'PWA permission owner')
  await signIn(page, user)
  const space = await createSpace(page, 'Unpublished app', undefined, 'note')
  await page.getByRole('button', { name: 'User menu for ' + user.name, exact: true }).click()
  await page.getByRole('menuitem', { name: 'Switch to dark theme', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('menu')).not.toBeVisible()
  await page.getByRole('link', { name: 'Installation settings', exact: true }).click()
  await page.getByRole('button', { name: 'PWA settings for Unpublished app' }).click()
  const dialog = page.getByRole('dialog', { name: 'PWA settings', exact: true })
  await dialog.getByLabel('Enable PWA', { exact: true }).check()
  await dialog.getByLabel(/I understand that the app name/).check()
  await page.route('**/apps/*/pwa', route => route.fulfill({ status: 500, json: { message: 'Test failure' } }))
  await dialog.getByRole('button', { name: 'Save PWA settings' }).click()
  await expect(dialog.getByRole('alert')).toContainText('Unable to update apps')
  await expect(dialog.getByLabel('App and installation name', { exact: true })).toHaveValue('Unpublished app')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: testInfo.outputPath('pwa-settings-dark.png'), animations: 'disabled' })
  await page.unroute('**/apps/*/pwa')
  const owner = await environment.app.db.selectFrom('users').select('id').where('email', '=', user.email).executeTakeFirstOrThrow()
  const stored = await environment.app.db.selectFrom('spaces').select(['id', 'namespace_id']).where('slug', '=', space.slug).executeTakeFirstOrThrow()
  await environment.app.db.updateTable('namespace_members').set({ role: 'member' }).where('namespace_id', '=', stored.namespace_id).where('user_id', '=', owner.id).execute()
  await environment.app.db.updateTable('space_members').set({ role: 'writer' }).where('space_id', '=', stored.id).where('user_id', '=', owner.id).execute()
  await dialog.getByRole('button', { name: 'Save PWA settings' }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('heading', { name: 'Access denied' })).toBeVisible()
  expect((await environment.app.db.selectFrom('space_apps').select('pwa').where('id', '=', stored.id).executeTakeFirstOrThrow()).pwa.enabled).toBe(false)
})
