import type { Page } from '@playwright/test'
import { test, expect } from './fixtures.js'
import { register, signIn, signOut } from './helpers.js'

async function simulateOutage(page: Page, path: string, method: string, once = true) {
  let pending = true
  await page.route('**' + path, async route => {
    if (pending && route.request().method() === method) {
      if (once) pending = false
      await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ message: 'Temporary outage' }) })
    } else await route.continue()
  })
  return () => { pending = false }
}

test('login and profile saves preserve inputs after a temporary failure', async ({ page }) => {
  const user = await register(page, 'Retry owner')
  await simulateOutage(page, '/api/auth/login', 'POST')
  await page.getByLabel('Email', { exact: true }).fill(user.email)
  await page.getByLabel('Password', { exact: true }).fill(user.password)
  const login = page.getByRole('main').getByRole('button', { name: 'Sign in', exact: true })
  await login.click()
  await expect(page.getByRole('alert')).toContainText('Unable to connect')
  await expect(page.getByLabel('Email', { exact: true })).toHaveValue(user.email)
  await login.click()
  await expect(page.getByRole('button', { name: 'User menu for ' + user.name })).toBeVisible()
  await page.goto('/settings/profile')
  await simulateOutage(page, '/api/auth/me', 'PATCH')
  await page.getByLabel('Display name', { exact: true }).fill('Retried name')
  const save = page.getByRole('button', { name: 'Save changes', exact: true })
  await save.click()
  await expect(page.getByRole('alert')).toContainText('Unable to save')
  await expect(page.getByLabel('Display name', { exact: true })).toHaveValue('Retried name')
  await expect(page.getByRole('button', { name: 'User menu for ' + user.name })).toBeVisible()
  await save.click()
  await expect(page.getByRole('status')).toHaveText('Profile saved.')
  await page.reload()
  await expect(page.getByLabel('Display name', { exact: true })).toHaveValue('Retried name')
})

test('token listing, creation and revocation can retry without losing the form', async ({ page }) => {
  await signIn(page, await register(page, 'Token retry owner'))
  // Keep reads unavailable until the error is visible, including remount/refetch requests.
  const recover = await simulateOutage(page, '/api/auth/tokens', 'GET', false)
  await page.goto('/settings/applications')
  await expect(page.getByRole('heading', { name: 'Unable to load tokens', exact: true })).toBeVisible()
  recover()
  await page.getByRole('button', { name: 'Try again', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'No access tokens yet', exact: true })).toBeVisible()
  await simulateOutage(page, '/api/auth/tokens', 'POST')
  await page.getByLabel('Name', { exact: true }).fill('Retry token')
  await page.getByLabel('Permissions', { exact: true }).selectOption('write')
  await page.getByLabel('Expires in', { exact: true }).selectOption('90')
  await page.getByRole('button', { name: 'Create token', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Unable to complete')
  await expect(page.getByLabel('Name', { exact: true })).toHaveValue('Retry token')
  await expect(page.getByLabel('Permissions', { exact: true })).toHaveValue('write')
  await expect(page.getByLabel('Expires in', { exact: true })).toHaveValue('90')
  await page.getByRole('button', { name: 'Create token', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Your token is ready', exact: true })).toBeVisible()
  // A denied clipboard permission still leaves a selectable one-time secret.
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => { throw new Error('Permission denied') } } }))
  await page.getByRole('button', { name: 'Copy access token', exact: true }).click()
  await expect(page.getByText('Select and copy the text manually.', { exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'New access token', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('textbox', { name: 'New access token', exact: true })).toHaveCount(0)
  const list = await (await page.request.get('/api/auth/tokens')).json()
  expect(list).toHaveLength(1)
  expect(list[0].scopes).toEqual(['git:read', 'git:write'])
  await simulateOutage(page, '/api/auth/tokens/' + list[0].id, 'DELETE')
  await page.getByRole('button', { name: 'Revoke Retry token', exact: true }).click()
  await page.getByRole('button', { name: 'Revoke token', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Unable to complete')
  await page.getByRole('button', { name: 'Revoke token', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Token revoked.')
  await page.reload()
  await expect(page.getByText('Revoked', { exact: true })).toBeVisible()
})

for (const section of ['profile', 'applications']) {
  test(`expired sessions return to ${section} after signing in again`, async ({ page }) => {
    const user = await register(page, 'Expired session owner')
    await signIn(page, user)
    await page.goto('/settings/' + section)
    const field = page.getByLabel(section === 'profile' ? 'Display name' : 'Name', { exact: true })
    await field.fill('Expired request')
    // Expire the real cookie without changing the already-rendered UI.
    expect((await page.request.post('/api/auth/logout')).status()).toBe(204)
    await page.getByRole('button', { name: section === 'profile' ? 'Save changes' : 'Create token', exact: true }).click()
    await expect(page).toHaveURL(/\/login$/)
    await page.getByLabel('Email', { exact: true }).fill(user.email)
    await page.getByLabel('Password', { exact: true }).fill(user.password)
    await page.getByRole('main').getByRole('button', { name: 'Sign in', exact: true }).click()
    await expect(page).toHaveURL(new RegExp('/settings/' + section + '$'))
    expect((await (await page.request.get('/api/auth/me')).json()).displayName).toBe(user.name)
    expect(await (await page.request.get('/api/auth/tokens')).json()).toEqual([])
  })
}

test('switching accounts isolates profile edits and access tokens', async ({ page }) => {
  const owner = await register(page, 'First settings owner')
  await signIn(page, owner)
  const first = await (await page.request.get('/api/auth/me')).json()
  await page.goto('/settings/applications')
  await page.getByLabel('Name', { exact: true }).fill('First account token')
  await page.getByRole('button', { name: 'Create token', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Your token is ready', exact: true })).toBeVisible()
  const tokens = await (await page.request.get('/api/auth/tokens')).json()
  await signOut(page, owner)
  const other = await register(page, 'Second settings owner')
  await signIn(page, other)
  await page.goto('/settings/applications')
  await expect(page.getByRole('heading', { name: 'No access tokens yet', exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'New access token', exact: true })).toHaveCount(0)
  expect((await page.request.delete('/api/auth/tokens/' + tokens[0].id)).status()).toBe(404)
  await page.goto('/settings/profile')
  await expect(page.getByLabel('Display name', { exact: true })).toHaveValue(other.name)
  await page.getByLabel('Display name', { exact: true }).fill('Second updated')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Profile saved.')
  const unchanged = await (await page.request.get('/api/users/' + first.id)).json()
  expect(unchanged.displayName).toBe(owner.name)
  await signOut(page, { ...other, name: 'Second updated' })
  await signIn(page, owner)
  await page.goto('/settings/applications')
  await expect(page.getByText('First account token', { exact: true })).toBeVisible()
  await expect(page.getByText('Active', { exact: true })).toBeVisible()
})
