import { randomUUID } from 'node:crypto'
import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { GetSpace200 } from '../src/api/generated/api.schemas.js'
import { test, expect } from './fixtures.js'
import { createSpace, openSettings, register, signIn, signOut } from './helpers.js'

test('register, sign in, create a Space and restore the session on reload', async ({ page }) => {
  const user = await register(page, 'Browser owner')
  await page.getByLabel('Password', { exact: true }).fill('wrong-password')
  await page.getByRole('main').getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Incorrect email or password.')
  await signIn(page, user)
  const space = await createSpace(page, 'Browser project')
  await expect(page.getByRole('heading', { name: 'Push your first commit', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: 'User menu for ' + user.name, exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Browser project', exact: true })).toBeVisible()
  await signOut(page, user)
  await page.goto(space.url)
  await expect(page.getByRole('heading', { name: 'Sign in to view this Space', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Settings', exact: true })).toHaveCount(0)
})

test('Space settings persist the name, visibility and default branch', async ({ page, request, environment }) => {
  const user = await register(page, 'Settings owner')
  await signIn(page, user)
  const space = await createSpace(page, 'Settings project')
  await openSettings(page)
  await expect(page.getByText('Push your first branch to choose a default branch.', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save default branch', exact: true })).toHaveCount(0)

  // Seed real Git branches; clone/push protocol is covered by test:integration.
  const metadataResponse = await page.request.get(`/api/namespaces/${space.account}/spaces/${space.slug}`)
  expect(metadataResponse.ok()).toBeTruthy()
  const metadata = await metadataResponse.json() as GetSpace200
  const source = join(environment.root, 'settings-seed-' + metadata.id)
  await environment.git(['clone', join(environment.root, 'data', metadata.id), source])
  for (const [branch, content] of [['main', '# Main content\n'], ['release', '# Release content\n']] as const) {
    await writeFile(join(source, 'README.md'), content)
    await environment.git(['-C', source, 'add', '.'])
    await environment.git(['-C', source, 'commit', '-m', branch])
    await environment.git(['-C', source, 'push', 'origin', 'HEAD:' + branch])
  }
  await page.getByRole('button', { name: 'Refresh branches', exact: true }).click()
  await expect(page.getByText('Used when browsing this Space and cloning the repository. The default branch is protected against force pushes and deletion. Changing it moves this protection to the selected branch.', { exact: true })).toBeVisible()
  await page.getByLabel('Default branch', { exact: true }).selectOption('release')
  await page.getByRole('button', { name: 'Save default branch', exact: true }).click()
  await expect(page.getByText('Default branch saved.', { exact: true })).toBeVisible()
  await page.getByLabel('Name', { exact: true }).fill('Renamed project')
  await page.getByLabel('Visibility', { exact: true }).selectOption('public')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('Changes saved.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Name', { exact: true })).toHaveValue('Renamed project')
  await expect(page.getByLabel('Visibility', { exact: true })).toHaveValue('public')
  await expect(page.getByLabel('Default branch', { exact: true })).toHaveValue('release')
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeDisabled()
  expect((await request.get(`/api/namespaces/${space.account}/spaces/${space.slug}`)).status()).toBe(200)
  let busyReplies = 0
  await page.route(`**/api/namespaces/${space.account}/spaces/${space.slug}/git`, async route => {
    if (busyReplies++ < 2) await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ statusCode: 503, code: 'GIT_BUSY', error: 'Service Unavailable', message: 'Git is busy. Please retry shortly.' }) })
    else await route.continue()
  })
  await page.getByRole('link', { name: 'Back to Space', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(space.url + '$'))
  await expect(page.getByRole('heading', { name: 'Renamed project', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Release content', exact: true })).toBeVisible()
  await expect.poll(() => busyReplies).toBeGreaterThanOrEqual(3)
  await expect(page.getByRole('button', { name: 'Delete Space', exact: true })).toHaveCount(0)
  await openSettings(page)
  await page.getByLabel('Visibility', { exact: true }).selectOption('private')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByText('Changes saved.', { exact: true })).toBeVisible()
  expect((await request.get(`/api/namespaces/${space.account}/spaces/${space.slug}`)).status()).toBe(401)
})

test('organization and Space membership work across accounts', async ({ page }) => {
  test.setTimeout(90_000)
  const member = await register(page, 'Browser teammate')
  // Register the owner in the same browser without signing the member in yet.
  const owner = await register(page, 'Team owner')
  await signIn(page, owner)
  const organization = 'browser-' + randomUUID().slice(0, 8)
  await page.getByRole('button', { name: 'Create menu', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Create organization', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Browser team')
  await page.getByLabel('URL name', { exact: true }).fill(organization)
  await page.getByRole('button', { name: 'Create organization', exact: true }).click()
  await expect(page).toHaveURL(new RegExp('/' + organization + '$'))
  await page.getByRole('link', { name: 'Members', exact: true }).click()
  await page.getByLabel('Member email', { exact: true }).fill(member.email)
  await page.getByRole('button', { name: 'Add member', exact: true }).click()
  await expect(page.getByText('Member added.', { exact: true })).toBeVisible()
  await page.getByLabel('Member email', { exact: true }).fill(member.email)
  await page.getByRole('button', { name: 'Add member', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('This user is already a member.')
  await expect(page.getByRole('button', { name: 'Remove ' + owner.email, exact: true })).toHaveCount(0)
  const space = await createSpace(page, 'Shared project', organization)
  await openSettings(page)
  await page.getByLabel('Member email', { exact: true }).fill(member.email)
  await page.getByRole('button', { name: 'Add member', exact: true }).click()
  await expect(page.getByText('Member added.', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Role for ' + member.email, { exact: true })).toHaveValue('reader')

  await signOut(page, owner)
  await signIn(page, member)
  await page.getByRole('link', { name: 'Browser team', exact: true }).click()
  await page.getByRole('link').filter({ hasText: 'Shared project' }).click()
  await expect(page.getByRole('heading', { name: 'Shared project', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Settings', exact: true })).toHaveCount(0)
  await page.goto(space.url + '/settings')
  await expect(page.getByRole('heading', { name: 'Access denied', exact: true })).toBeVisible()
  await signOut(page, member)
  await signIn(page, owner)
  await page.goto(space.url + '/settings')
  await page.getByLabel('Role for ' + member.email, { exact: true }).selectOption('writer')
  await expect(page.getByText('Role updated.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Role for ' + member.email, { exact: true })).toHaveValue('writer')
  await page.getByRole('button', { name: 'Remove ' + member.email, exact: true }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByLabel('Role for ' + member.email, { exact: true })).toHaveValue('writer')
  await page.getByRole('button', { name: 'Remove ' + member.email, exact: true }).click()
  await page.getByRole('button', { name: 'Remove member', exact: true }).click()
  await expect(page.getByText('Member removed.', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Role for ' + member.email, { exact: true })).toHaveCount(0)

  await signOut(page, owner)
  await signIn(page, member)
  await page.goto(space.url)
  await expect(page.getByRole('heading', { name: 'Access denied', exact: true })).toBeVisible()
  await signOut(page, member)
  await signIn(page, owner)
  await page.goto('/' + organization + '?tab=members')
  await page.getByRole('button', { name: 'Remove ' + member.email, exact: true }).click()
  await page.getByRole('button', { name: 'Remove member', exact: true }).click()
  await expect(page.getByText('Member removed.', { exact: true })).toBeVisible()
  await signOut(page, owner)
  await signIn(page, member)
  await expect(page.getByRole('link', { name: 'Browser team', exact: true })).toHaveCount(0)
})
