import { test, expect } from './fixtures.js'
import { createSpace, register, signIn } from './helpers.js'
import { epubFixture, pdfFixture } from './ebook-fixtures.js'

test('PDF continuously scrolls long books with bounded canvas rendering', async ({ page, environment }) => {
  const user = await register(page, 'Continuous reader')
  await signIn(page, user)
  const space = await createSpace(page, 'Long books', undefined, 'ebook')
  const base = `/api/namespaces/${space.account}/spaces/${space.slug}`
  const { id } = await (await page.request.get(base)).json() as { id: string }
  expect((await page.request.put(base + '/objects/long.pdf', {
    data: pdfFixture(20), headers: { 'content-type': 'application/pdf' },
  })).status()).toBe(201)
  await page.goto(`${environment.webOrigin}/app/ebook/${id}/`)
  await page.getByRole('link', { name: 'Read long.pdf', exact: true }).click()
  const reader = page.getByRole('region', { name: 'PDF pages' })
  await expect(reader.locator('[data-pdf-page]')).toHaveCount(20)
  await expect(page.getByRole('img', { name: 'PDF page 1', exact: true })).toBeVisible()
  await expect(page.getByText('This PDF has no table of contents.', { exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Thumbnails', exact: true }).click()
  const thumbnails = page.getByRole('tabpanel', { name: 'Thumbnails', exact: true })
  await expect(thumbnails.getByRole('img', { name: 'Thumbnail of page 1', exact: true })).toBeVisible()
  await expect.poll(() => thumbnails.locator('canvas').count()).toBeLessThan(7)
  await expect.poll(() => reader.locator('canvas').count()).toBeLessThan(6)
  await reader.evaluate(element => { element.scrollTop = element.scrollHeight })
  await expect(page.getByRole('textbox', { name: 'Page number', exact: true })).toHaveValue('20')
  await expect(page.getByRole('img', { name: 'PDF page 20', exact: true })).toBeVisible()
  await expect(page.getByRole('img', { name: 'PDF page 1', exact: true })).toHaveCount(0)
  await expect.poll(() => reader.locator('canvas').count()).toBeLessThan(6)
  await expect(thumbnails.getByRole('img', { name: 'Thumbnail of page 20', exact: true })).toBeVisible()
  await expect(thumbnails.getByRole('img', { name: 'Thumbnail of page 1', exact: true })).toHaveCount(0)
  await expect.poll(() => thumbnails.locator('canvas').count()).toBeLessThan(7)
  await thumbnails.getByRole('button', { name: 'Go to page 19', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Page number', exact: true })).toHaveValue('19')
  await page.getByRole('button', { name: 'Zoom in' }).click()
  await expect(page.getByRole('textbox', { name: 'Page number', exact: true })).toHaveValue('19')
  await page.getByRole('button', { name: 'Auto zoom' }).click()
  await expect(page.getByRole('button', { name: 'Auto zoom' })).toHaveText('Auto')
  await expect(page.getByRole('textbox', { name: 'Page number', exact: true })).toHaveValue('19')
  await reader.evaluate(element => { element.scrollTop = 0 })
  await expect(page.getByRole('textbox', { name: 'Page number', exact: true })).toHaveValue('1')
  await expect(page.locator('[aria-busy="true"]')).toHaveCount(0)
  await expect(page.getByRole('img', { name: 'PDF page 1', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Toggle sidebar' }).click()
  await expect(page.getByRole('navigation', { name: 'PDF navigation' })).toBeHidden()
  await page.getByRole('button', { name: 'Toggle sidebar' }).click()
  await expect(page.getByRole('tab', { name: 'Thumbnails', exact: true })).toHaveAttribute('aria-selected', 'true')
})

test('Ebook Space opens a library with EPUB chapters, safe content and PDF page previews', async ({ page: manager, browser, environment }, testInfo) => {
  test.setTimeout(120_000)
  const user = await register(manager, 'Book owner')
  await signIn(manager, user)
  const space = await createSpace(manager, 'Reading room', undefined, 'ebook')
  const base = `/api/namespaces/${space.account}/spaces/${space.slug}`
  const { id } = await (await manager.request.get(base)).json() as { id: string }
  await expect(manager.getByRole('region', { name: 'Files', exact: true })).toBeVisible()
  await expect(manager.getByRole('region', { name: 'Book reader' })).toHaveCount(0)
  const popup = manager.waitForEvent('popup')
  await manager.getByRole('link', { name: 'Open Reading room (opens in a new tab)' }).click()
  const page = await popup
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await expect(page).toHaveURL(`${environment.webOrigin}/app/ebook/${id}/`)
  await expect(page.getByRole('heading', { name: 'Your bookshelf is ready' })).toBeVisible()
  for (const [name, mimeType, buffer] of [
    ['A quiet journey.epub', 'application/octet-stream', epubFixture()],
    ['Field notes.pdf', 'application/pdf', pdfFixture(2, true)],
  ] as const) {
    await manager.getByLabel('Choose a file to upload', { exact: true }).setInputFiles({ name, mimeType, buffer })
    await expect(manager.getByRole('status').filter({ hasText: `Uploaded ${name}.` })).toBeVisible()
  }
  expect((await manager.request.put(base + '/objects/not-a-book.txt', { data: 'notes', headers: { 'content-type': 'text/plain' } })).status()).toBe(201)
  await page.getByRole('button', { name: 'Reload', exact: true }).click()
  await expect(page.getByRole('list', { name: 'Books' }).getByRole('link')).toHaveCount(2)
  await page.screenshot({ path: testInfo.outputPath('ebook-library.png'), fullPage: true, animations: 'disabled' })
  const external: string[] = []
  page.on('request', request => { if (request.url().includes('example.invalid')) external.push(request.url()) })
  const book = page.getByRole('link', { name: 'Read A quiet journey.epub', exact: true })
  const bookPath = await book.getAttribute('href')
  expect(bookPath).toMatch(new RegExp(`^/app/ebook/${id}/book/[a-f0-9-]+$`))
  await book.click()
  await expect(page).toHaveURL(environment.webOrigin + bookPath)
  await expect(page.getByRole('list', { name: 'Books' })).toHaveCount(0)
  const frame = page.frameLocator('iframe[title="EPUB chapter"]')
  await expect(frame.getByRole('heading', { name: 'The beginning' })).toBeVisible()
  await page.goBack()
  await expect(book).toBeVisible()
  await expect(page.getByRole('region', { name: 'Book reader' })).toHaveCount(0)
  await page.goForward()
  await expect(page).toHaveURL(environment.webOrigin + bookPath)
  await expect(frame.getByRole('heading', { name: 'The beginning' })).toBeVisible()
  await expect(frame.getByText('Every journey begins with a single page.')).toBeVisible()
  await expect(frame.locator('script, form, input, [onerror], [href], img[src]')).toHaveCount(0)
  expect(external).toEqual([])
  await page.getByRole('button', { name: 'Increase text size' }).click()
  await expect(frame.locator('body')).toHaveCSS('font-size', '20px')
  await page.getByRole('navigation', { name: 'Chapters', exact: true }).getByRole('button', { name: '2. A new horizon', exact: true }).click()
  await expect(frame.getByRole('heading', { name: 'A new horizon' })).toBeVisible()
  await page.getByRole('navigation', { name: 'Chapters', exact: true }).getByRole('button', { name: '1. The beginning', exact: true }).click()
  await expect(frame.getByRole('heading', { name: 'The beginning' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('ebook-reading.png'), fullPage: true, animations: 'disabled' })
  await page.evaluate(() => localStorage.setItem('enspatium-color-mode', 'dark'))
  await page.reload()
  await expect(frame.locator('body')).toHaveCSS('background-color', 'rgb(11, 15, 13)')
  await page.screenshot({ path: testInfo.outputPath('ebook-dark.png'), fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('navigation', { name: 'Chapters', exact: true })).toBeHidden()
  await page.getByRole('button', { name: 'Toggle sidebar' }).click()
  await page.getByRole('navigation', { name: 'Chapters', exact: true }).getByRole('button', { name: '2. A new horizon', exact: true }).click()
  await expect(frame.getByRole('heading', { name: 'A new horizon' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Chapters', exact: true })).toBeHidden()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('ebook-epub-mobile.png'), fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.getByRole('link', { name: /Back to library/ }).click()
  await expect(book).toBeVisible()
  await page.getByRole('button', { name: 'PDF', exact: true }).click()
  await expect(page.getByRole('list', { name: 'Books' }).getByRole('link')).toHaveCount(1)
  await page.getByRole('link', { name: 'Read Field notes.pdf', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Page number', exact: true })).toHaveValue('1')
  // These resources must be served locally in dev and copied into production builds.
  for (const path of ['/pdfjs/cmaps/UniCNS-UCS2-H.bcmap', '/pdfjs/standard_fonts/FoxitSerif.pfb', '/pdfjs/wasm/openjpeg.wasm']) {
    const asset = await page.request.get(path)
    expect(asset.status()).toBe(200)
    expect(asset.headers()['content-type']).not.toContain('text/html')
  }
  await expect(page.locator('[aria-busy="true"]')).toHaveCount(0)
  const first = await page.getByRole('img', { name: 'PDF page 1', exact: true }).evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL())
  expect(first.length).toBeGreaterThan(1000)
  const toc = page.getByRole('tabpanel', { name: 'Table of contents', exact: true })
  await expect(page.getByRole('tab', { name: 'Table of contents', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(toc.getByRole('button', { name: 'The beginning', exact: true })).toBeVisible()
  await toc.getByRole('button', { name: 'A new horizon', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Page number', exact: true })).toHaveValue('2')
  await expect(page.locator('[aria-busy="true"]')).toHaveCount(0)
  expect(await page.getByRole('img', { name: 'PDF page 2', exact: true }).evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL())).not.toBe(first)
  const pdfPages = page.getByRole('region', { name: 'PDF pages' })
  await expect(pdfPages.locator('[data-pdf-page]')).toHaveCount(2)
  await pdfPages.evaluate(element => { element.scrollTop = 0 })
  await expect(page.getByRole('textbox', { name: 'Page number', exact: true })).toHaveValue('1')
  await pdfPages.evaluate(element => { element.scrollTop = element.scrollHeight })
  await expect(page.getByRole('textbox', { name: 'Page number', exact: true })).toHaveValue('2')
  await page.getByRole('button', { name: 'Zoom in' }).click()
  await expect(page.getByText('125%', { exact: true })).toBeVisible()
  await expect(page.locator('[aria-busy="true"]')).toHaveCount(0)
  const renderedPage = page.getByRole('img', { name: 'PDF page 2', exact: true })
  await expect.poll(() => renderedPage.evaluate((canvas: HTMLCanvasElement) => {
    if (!canvas.width || !canvas.height) return false
    const pixel = canvas.getContext('2d')!.getImageData(0, 0, 1, 1).data
    return pixel[0] === 255 && pixel[1] === 255 && pixel[2] === 255 && pixel[3] === 255
  })).toBe(true)
  const readerHeader = page.locator('header[aria-label="Reader header"]')
  await expect(readerHeader.getByRole('link', { name: 'Back to library' })).toBeVisible()
  await expect(readerHeader.getByRole('heading', { name: 'Field notes.pdf' })).toBeVisible()
  await expect(readerHeader.getByRole('link', { name: 'Download book' })).toHaveAttribute('download', 'Field notes.pdf')
  expect(await readerHeader.evaluate(element => element.firstElementChild?.getAttribute('aria-label'))).toBe('Back to library')
  await expect(readerHeader.getByRole('button', { name: 'Zoom in' })).toHaveCount(0)
  const controls = page.getByRole('toolbar', { name: 'Reading controls' })
  await expect(controls.getByRole('button', { name: 'Auto zoom' })).toBeVisible()
  const headerBounds = (await readerHeader.boundingBox())!
  const controlsBounds = (await controls.boundingBox())!
  expect(controlsBounds.y).toBeGreaterThan(headerBounds.y + headerBounds.height)
  await page.getByRole('button', { name: 'Auto zoom' }).click()
  await expect(page.getByRole('button', { name: 'Auto zoom' })).toHaveText('Auto')
  await expect(page.locator('[aria-busy="true"]')).toHaveCount(0)
  await toc.getByRole('button', { name: 'The beginning', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Page number', exact: true })).toHaveValue('1')
  await expect(page.locator('[aria-busy="true"]')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('ebook-pdf.png'), fullPage: true, animations: 'disabled' })
  // Icon tabs support both mouse and keyboard, and thumbnails are actual rendered pages.
  await page.getByRole('tab', { name: 'Table of contents', exact: true }).focus()
  await page.keyboard.press('ArrowLeft')
  await expect(page.getByRole('tab', { name: 'Thumbnails', exact: true })).toHaveAttribute('aria-selected', 'true')
  const thumbnail = page.getByRole('img', { name: 'Thumbnail of page 1', exact: true })
  await expect.poll(() => thumbnail.evaluate((canvas: HTMLCanvasElement) => {
    if (!canvas.width || !canvas.height) return false
    const pixels = canvas.getContext('2d')!.getImageData(0, 0, canvas.width, canvas.height).data
    return pixels[0] === 255 && pixels[3] === 255 && pixels.some((value, index) => index % 4 !== 3 && value < 200)
  })).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('ebook-pdf-thumbnails.png'), fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('navigation', { name: 'PDF navigation', exact: true })).toBeHidden()
  await page.getByRole('button', { name: 'Toggle sidebar' }).click()
  await page.getByRole('tabpanel', { name: 'Thumbnails', exact: true }).getByRole('button', { name: 'Go to page 2', exact: true }).click()
  await expect(page.getByRole('navigation', { name: 'PDF navigation', exact: true })).toBeHidden()
  await expect(page.getByRole('textbox', { name: 'Page number', exact: true })).toHaveValue('2')
  await expect(page.locator('[aria-busy="true"]')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= window.innerHeight)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('ebook-mobile.png'), fullPage: true, animations: 'disabled' })
  await page.getByRole('link', { name: /Back to library/ }).click()
  await expect(page).toHaveURL(`${environment.webOrigin}/app/ebook/${id}/?format=pdf`)
  await page.getByRole('button', { name: 'All books', exact: true }).click()
  await page.getByLabel('Search books').fill('quiet')
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await expect(page.getByRole('list', { name: 'Books' }).getByRole('link')).toHaveCount(1)
  await book.click()
  await page.getByRole('link', { name: /Back to library/ }).click()
  await expect(page).toHaveURL(`${environment.webOrigin}/app/ebook/${id}/?search=quiet`)
  const guestContext = await browser.newContext()
  try {
    const guest = await guestContext.newPage()
    await guest.goto(environment.webOrigin + bookPath)
    await expect(guest.getByRole('heading', { name: 'Sign in to open this app' })).toBeVisible()
    expect((await manager.request.patch(base, { data: { visibility: 'public' } })).status()).toBe(200)
    await guest.reload()
    await expect(guest.frameLocator('iframe').getByRole('heading', { name: 'The beginning' })).toBeVisible()
    expect((await manager.request.patch(base, { data: { visibility: 'private' } })).status()).toBe(200)
    await guest.reload()
    await expect(guest.getByRole('heading', { name: /^Sign in to (read this book|open this app)$/ })).toBeVisible()
    await expect(guest.locator('iframe')).toHaveCount(0)
    await guest.getByRole('link', { name: 'Sign in', exact: true }).click()
    await guest.getByLabel('Email', { exact: true }).fill(user.email)
    await guest.getByLabel('Password', { exact: true }).fill(user.password)
    await guest.getByRole('main').getByRole('button', { name: 'Sign in', exact: true }).click()
    await expect(guest).toHaveURL(environment.webOrigin + bookPath)
    await expect(guest.frameLocator('iframe').getByRole('heading', { name: 'The beginning' })).toBeVisible()
  } finally { await guestContext.close() }
  await page.getByLabel('Search books').fill('')
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  for (const [key, mime] of [['broken.epub', 'application/epub+zip'], ['broken.pdf', 'application/pdf']] as const) {
    expect((await manager.request.put(base + '/objects/' + key, { data: 'invalid book', headers: { 'content-type': mime } })).status()).toBe(201)
    await page.getByRole('button', { name: 'Reload', exact: true }).click()
    await page.getByRole('link', { name: `Read ${key}`, exact: true }).click()
    await expect(page.getByRole('alert')).toBeVisible()
    await page.getByRole('link', { name: /Back to library/ }).click()
  }
  // Book IDs stay resolvable after a reload even when the book was on a later shelf page.
  for (let index = 0; index < 31; index++) {
    expect((await manager.request.put(base + `/objects/Shelf-${String(index).padStart(2, '0')}.epub`, { data: epubFixture(), headers: { 'content-type': 'application/epub+zip' } })).status()).toBe(201)
  }
  expect((await manager.request.put(base + '/objects/Z-last.epub', { data: epubFixture(), headers: { 'content-type': 'application/epub+zip' } })).status()).toBe(201)
  await page.getByRole('button', { name: 'Reload', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Read Z-last.epub', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Next page', exact: true }).click()
  const shelfUrl = page.url()
  const lastBook = page.getByRole('link', { name: 'Read Z-last.epub', exact: true })
  const lastPath = await lastBook.getAttribute('href')
  await lastBook.click()
  await page.reload()
  await expect(page).toHaveURL(environment.webOrigin + lastPath)
  await expect(frame.getByRole('heading', { name: 'The beginning' })).toBeVisible()
  await expect(page.getByRole('list', { name: 'Books' })).toHaveCount(0)
  await page.getByRole('link', { name: /Back to library/ }).click()
  await expect(page).toHaveURL(shelfUrl)
  await lastBook.click()
  expect((await manager.request.delete(base + '/objects/Z-last.epub')).status()).toBe(204)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Book not found' })).toBeVisible()
  await expect(page.locator('iframe')).toHaveCount(0)
  await page.goto(`${environment.webOrigin}/app/ebook/${id}/book/not-an-id`)
  await expect(page.getByRole('heading', { name: 'Book not found' })).toBeVisible()
  await page.goto(`${environment.webOrigin}${bookPath}/unknown`)
  await expect(page.getByRole('heading', { name: 'Page not found' })).toBeVisible()
  await page.getByRole('link', { name: 'Back to app' }).click()
  await expect(page).toHaveURL(`${environment.webOrigin}/app/ebook/${id}/`)
  expect(errors, 'Uncaught reader errors').toEqual([])
  await page.close()
})
