import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { test, expect } from './fixtures.js'
import { createSpace, register, signIn } from './helpers.js'

test('file rows show their own commits and dates at the selected snapshot', async ({ page, environment }, testInfo) => {
  await signIn(page, await register(page, 'Tree owner'))
  const space = await createSpace(page, 'File history')
  const base = `/api/namespaces/${space.account}/spaces/${space.slug}`
  const { id } = await (await page.request.get(base)).json()
  const source = join(environment.root, 'tree-history')
  await environment.git(['clone', join(environment.root, 'data', id), source])
  const git = (args: string[]) => environment.git(['-C', source, ...args])
  await mkdir(join(source, 'docs'))
  await writeFile(join(source, 'docs', 'guide.md'), '# Guide\n')
  await writeFile(join(source, 'README.md'), '# Welcome\n')
  await git(['add', '.']); await git(['commit', '-m', 'Initial files'])
  const first = (await git(['rev-parse', 'HEAD'])).stdout.trim()
  await git(['tag', 'v1'])
  await writeFile(join(source, 'README.md'), '# Updated\n')
  await git(['add', '.']); await git(['commit', '-m', 'Update README only'])
  const second = (await git(['rev-parse', 'HEAD'])).stdout.trim()
  await git(['push', 'origin', 'HEAD:main', '--tags'])
  await page.reload()
  const rows = page.getByRole('list', { name: 'Repository files' })
  const readme = rows.getByRole('listitem').filter({ has: page.getByRole('link', { name: 'README.md', exact: true }) })
  const docs = rows.getByRole('listitem').filter({ has: page.getByRole('link', { name: 'docs/ Folder', exact: true }) })
  await expect(readme.getByRole('link', { name: 'View commit for README.md: Update README only', exact: true })).toHaveAttribute('href', space.url + '/commit/' + second)
  await expect(docs.getByRole('link', { name: 'View commit for docs: Initial files', exact: true })).toHaveAttribute('href', space.url + '/commit/' + first)
  await expect(readme.locator('time')).toContainText(/ago|just now/)
  await readme.locator('time').hover()
  await expect(readme.locator('time')).toHaveAttribute('title', /\d{4}.*\d{1,2}:\d{2}/)
  const banner = page.getByLabel('Latest commit', { exact: true })
  expect((await banner.boundingBox())!.height).toBeLessThanOrEqual(48)
  const history = banner.getByRole('link', { name: '2 commits', exact: true })
  await expect(history).toHaveAttribute('href', space.url + '/branch/main/commits/at/' + second)
  await history.click()
  await expect(page.getByRole('region', { name: 'Commit history' })).toContainText('Update README only')
  await expect(page.getByRole('region', { name: 'Commit history' })).toContainText('Initial files')
  await page.goto(space.url)
  await expect(page.getByRole('heading', { name: 'Updated', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('file-commits.png'), fullPage: true })
  await docs.getByRole('link', { name: 'View commit for docs: Initial files', exact: true }).click()
  await expect(page).toHaveURL(environment.webOrigin + space.url + '/commit/' + first)
  await expect(page.getByRole('region', { name: 'Commit details' })).toContainText('Initial files')
  await page.goto(space.url + '/branch/main/tree/docs')
  await expect(rows.getByRole('link', { name: 'View commit for guide.md: Initial files', exact: true })).toBeVisible()
  await page.goto(space.url + '/tag/v1')
  await expect(readme.getByRole('link', { name: 'View commit for README.md: Initial files', exact: true })).toBeVisible()
  await expect(rows).not.toContainText('Update README only')
  await expect(banner.getByRole('link', { name: '1 commit', exact: true })).toHaveAttribute('href', space.url + '/tag/v1/commits/at/' + first)
  await banner.getByRole('link', { name: '1 commit', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Commit history' })).toContainText('Initial files')
  await expect(page.getByRole('region', { name: 'Commit history' })).not.toContainText('Update README only')
  await page.goto(space.url + '/tag/v1')
  await page.evaluate(() => localStorage.setItem('enspatium-color-mode', 'dark'))
  await page.reload()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(rows).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Welcome', exact: true })).toBeVisible()
  await expect(banner.getByRole('link', { name: '1 commit', exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('file-commits-mobile-dark.png'), fullPage: true })
})
