import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { GetSpace200 } from '../src/api/generated/api.schemas.js'
import { test, expect } from './fixtures.js'
import { createSpace, register, signIn, signOut } from './helpers.js'

test('compare branch/tag snapshots, navigate changed files, swap and refresh after a push', async ({ page, environment, request }, testInfo) => {
  const user = await register(page, 'Compare owner')
  await signIn(page, user)
  const space = await createSpace(page, 'Compare repository')
  const api = `/api/namespaces/${space.account}/spaces/${space.slug}`
  const metadata = await (await page.request.get(api)).json() as GetSpace200
  await page.goto(space.url + '?view=compare')
  await expect(page.getByRole('heading', { name: 'No references to compare', exact: true })).toBeVisible()
  const work = join(environment.root, 'compare-seed')
  await environment.git(['clone', join(environment.root, 'data', metadata.id), work])
  const git = (args: string[]) => environment.git(['-C', work, ...args])
  await writeFile(join(work, 'README.md'), '# Before\n')
  await writeFile(join(work, 'old name.txt'), 'Unchanged content\n')
  await writeFile(join(work, 'obsolete.txt'), 'Remove me\n')
  await git(['add', '.']); await git(['commit', '-m', 'Base version'])
  const base = (await git(['rev-parse', 'HEAD'])).stdout.trim()
  await git(['tag', '-a', 'release/首版', '-m', 'Release'])
  await writeFile(join(work, 'README.md'), '# After\n')
  await writeFile(join(work, '中文 #%.txt'), 'New Unicode file\n')
  await writeFile(join(work, 'image.bin'), new Uint8Array([0, 255, 0, 12]))
  await git(['mv', 'old name.txt', 'new name.txt']); await git(['rm', 'obsolete.txt'])
  await git(['add', '.']); await git(['commit', '-m', 'Target version'])
  const target = (await git(['rev-parse', 'HEAD'])).stdout.trim()
  await git(['push', 'origin', 'HEAD:main', 'HEAD:refs/heads/release/首版', '--tags'])
  expect((await request.get(api + '/git/diff?' + new URLSearchParams({ from: 'refs/tags/release/首版', to: 'refs/heads/release/首版' }))).status()).toBe(401)
  await page.goto(space.url)
  await expect(page.getByRole('heading', { name: 'After', exact: true })).toBeVisible()
  await page.getByRole('navigation', { name: 'Repository views' }).getByRole('link', { name: 'Compare', exact: true }).click()
  const comparison = page.getByRole('region', { name: 'Version comparison', exact: true })
  await expect(comparison.getByRole('heading', { name: 'Compare versions', exact: true })).toBeVisible()
  await comparison.getByLabel('Base', { exact: true }).selectOption('refs/tags/release/首版')
  await expect(comparison.getByLabel('Base', { exact: true })).toHaveValue('refs/tags/release/首版')
  await comparison.getByLabel('Target', { exact: true }).selectOption('refs/heads/release/首版')
  const changes = page.getByRole('navigation', { name: 'Changed files', exact: true })
  const diff = page.getByRole('region', { name: 'File diff', exact: true })
  await expect(comparison.getByRole('heading', { name: '5 changed files', exact: true })).toBeVisible()
  await expect(diff).toContainText('-# Before'); await expect(diff).toContainText('+# After')
  await expect.poll(() => new URL(page.url()).searchParams.get('base')).toBe(base)
  await expect.poll(() => new URL(page.url()).searchParams.get('head')).toBe(target)
  await changes.getByRole('link').filter({ hasText: '中文 #%.txt' }).click()
  await expect(diff).toContainText('+New Unicode file')
  await page.reload(); await expect(diff).toContainText('+New Unicode file')
  await changes.getByRole('link').filter({ hasText: 'new name.txt' }).click()
  await expect(diff).toContainText('rename from old name.txt')
  await changes.getByRole('link').filter({ hasText: 'image.bin' }).click()
  await expect(page.getByRole('heading', { name: 'Binary file changed', exact: true })).toBeVisible()
  await changes.getByRole('link').filter({ hasText: 'obsolete.txt' }).click()
  await expect(diff).toContainText('-Remove me')
  await changes.getByRole('link').filter({ hasText: 'README.md' }).click()
  await expect(diff).toContainText('+# After')
  const pinnedUrl = page.url()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('compare.png'), fullPage: true })
  await page.getByRole('button', { name: 'User menu for ' + user.name, exact: true }).click()
  await page.getByRole('menuitem', { name: 'Switch to dark theme', exact: true }).click()
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('compare-mobile.png'), fullPage: true })
  await writeFile(join(work, 'README.md'), '# New push\n')
  await git(['add', '.']); await git(['commit', '-m', 'New pushed version'])
  const latest = (await git(['rev-parse', 'HEAD'])).stdout.trim()
  await git(['push', 'origin', 'HEAD:refs/heads/release/首版'])
  await page.goto(pinnedUrl)
  await expect(diff).toContainText('+# After'); await expect(diff).not.toContainText('New push')
  await comparison.getByRole('button', { name: 'Refresh comparison', exact: true }).click()
  await expect(diff).toContainText('+# New push')
  await expect.poll(() => new URL(page.url()).searchParams.get('head')).toBe(latest)
  await comparison.getByRole('button', { name: 'Swap', exact: true }).click()
  await expect(diff).toContainText('-# New push'); await expect(diff).toContainText('+# Before')
  await comparison.getByLabel('Base', { exact: true }).selectOption('refs/tags/release/首版')
  await expect(page.getByRole('heading', { name: 'No file changes', exact: true })).toBeVisible()
  await page.goto(space.url + '?' + new URLSearchParams({ view: 'compare', from: 'refs/tags/missing', to: 'refs/heads/main' }))
  await expect(page.getByRole('heading', { name: 'Reference unavailable', exact: true })).toBeVisible()
  await comparison.getByLabel('Base', { exact: true }).selectOption('refs/tags/release/首版')
  await expect(diff).toContainText('+# After')
  // The service's bounded diff response remains a recoverable preview state.
  await writeFile(join(work, 'large.txt'), 'large change\n'.repeat(90_000))
  await git(['add', '.']); await git(['commit', '-m', 'Large change'])
  await git(['push', 'origin', 'HEAD:refs/heads/large'])
  await page.goto(space.url + '?' + new URLSearchParams({ view: 'compare', from: 'refs/tags/release/首版', to: 'refs/heads/large' }))
  await expect(page.getByRole('heading', { name: 'Comparison unavailable', exact: true })).toBeVisible()
  await expect(comparison).toContainText('1 MiB preview limit')
  await comparison.getByLabel('Target', { exact: true }).selectOption('refs/heads/main')
  await expect(diff).toContainText('+# After')
  await signOut(page, user)
  await page.goto(pinnedUrl)
  await expect(page.getByRole('heading', { name: 'Sign in to view this Space', exact: true })).toBeVisible()
})
