import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { GetSpace200 } from '../src/api/generated/api.schemas.js'
import { test, expect } from './fixtures.js'
import { createSpace, register, signIn } from './helpers.js'

test('browse branch history, initial and later changes, and reload a selected diff', async ({ page, environment }, testInfo) => {
  const user = await register(page, 'History owner')
  await signIn(page, user)
  const space = await createSpace(page, 'History project')
  const response = await page.request.get(`/api/namespaces/${space.account}/spaces/${space.slug}`)
  expect(response.ok()).toBeTruthy()
  const metadata = await response.json() as GetSpace200
  const source = join(environment.root, 'history-seed-' + metadata.id)
  const git = (args: string[]) => environment.git(['-C', source, ...args])
  await environment.git(['clone', join(environment.root, 'data', metadata.id), source])
  await writeFile(join(source, 'README.md'), '# Before\n')
  await writeFile(join(source, 'old name.txt'), 'Keep this content\n')
  await writeFile(join(source, 'obsolete.txt'), 'Remove this\n')
  await git(['add', '.'])
  await git(['commit', '-m', 'Initial content'])
  await git(['push', 'origin', 'HEAD:main'])
  await git(['branch', 'original'])
  await git(['push', 'origin', 'original'])
  await writeFile(join(source, 'README.md'), '# After\n<script>alert("unsafe")</script>\n')
  await writeFile(join(source, '中文.txt'), 'Hello from a Unicode file\n')
  await writeFile(join(source, 'image.bin'), new Uint8Array([0, 255, 0, 12]))
  await git(['mv', 'old name.txt', 'new name.txt'])
  await git(['rm', 'obsolete.txt'])
  await git(['add', '.'])
  await git(['commit', '-m', 'Update documentation'])
  await git(['push', 'origin', 'HEAD:main'])

  await page.reload()
  await page.getByRole('navigation', { name: 'Repository views' }).getByRole('link', { name: 'Commits', exact: true }).click()
  const history = page.getByRole('region', { name: 'Commit history', exact: true })
  await expect(history.getByRole('link').filter({ hasText: 'Update documentation' })).toBeVisible()
  await page.getByLabel('Branch', { exact: true }).selectOption('original')
  await expect(history.getByRole('link').filter({ hasText: 'Initial content' })).toBeVisible()
  await expect(history.getByRole('link').filter({ hasText: 'Update documentation' })).toHaveCount(0)
  await history.getByRole('link').filter({ hasText: 'Initial content' }).click()
  await expect(page.getByText('Initial commit', { exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'File diff', exact: true })).toContainText('+# Before')

  await page.getByRole('link', { name: 'Back to commits', exact: true }).click()
  await page.getByLabel('Branch', { exact: true }).selectOption('main')
  await history.getByRole('link').filter({ hasText: 'Update documentation' }).click()
  const changed = page.getByRole('navigation', { name: 'Changed files', exact: true })
  await changed.getByRole('link').filter({ hasText: 'README.md' }).click()
  const diff = page.getByRole('region', { name: 'File diff', exact: true })
  await expect(diff).toContainText('-# Before')
  await expect(diff).toContainText('+# After')
  await expect(diff).toContainText('+<script>alert("unsafe")</script>')
  await page.reload()
  await expect(diff).toContainText('+# After')
  await expect(changed.getByRole('link').filter({ hasText: 'README.md' })).toHaveAttribute('aria-current', 'page')
  await page.screenshot({ path: testInfo.outputPath('commit-diff.png'), fullPage: true })
  await changed.getByRole('link').filter({ hasText: 'image.bin' }).click()
  await expect(page.getByRole('heading', { name: 'Binary file changed', exact: true })).toBeVisible()
  await changed.getByRole('link').filter({ hasText: 'old name.txt → new name.txt' }).click()
  await expect(diff).toContainText('rename to new name.txt')
  await changed.getByRole('link').filter({ hasText: 'obsolete.txt' }).click()
  await expect(diff).toContainText('-Remove this')
  await changed.getByRole('link').filter({ hasText: '中文.txt' }).click()
  await expect(diff).toContainText('+Hello from a Unicode file')
  await page.goBack()
  await expect(diff).toContainText('-Remove this')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(changed).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('commit-diff-mobile.png'), fullPage: true })

  // Invalid deep links should offer recovery without showing stale content.
  const invalid = new URL(page.url())
  invalid.searchParams.set('commit', '0'.repeat(40))
  await page.goto(invalid.href)
  await expect(page.getByRole('heading', { name: 'Unable to load commits', exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'File diff', exact: true })).toHaveCount(0)
})
