import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { strFromU8, unzipSync } from 'fflate'
import { test, expect } from './fixtures.js'
import { createSpace, openSettings, register, signIn } from './helpers.js'

test('the displayed clone URL supports push, clone, default branch changes and browsing the same commits', async ({ page, environment }) => {
  test.setTimeout(90_000)
  await signIn(page, await register(page, 'Git workflow owner'))
  const space = await createSpace(page, 'Git workflow')
  await expect(page.getByRole('heading', { name: 'Push your first commit', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Clone', exact: true }).click()
  const remote = await page.getByRole('textbox', { name: 'Clone URL', exact: true }).inputValue()
  expect(remote).toBe(`${environment.webOrigin}/api/git/${space.account}/${space.slug}.git`)
  await expect(page.getByRole('link', { name: 'Download ZIP', exact: true })).toHaveCount(0)
  await page.getByRole('link', { name: 'Manage access tokens', exact: true }).click()
  await expect(page).toHaveURL(environment.webOrigin + '/settings/applications')
  await page.getByLabel('Name', { exact: true }).fill('Git workflow token')
  await page.getByLabel('Permissions', { exact: true }).selectOption('write')
  await page.getByRole('button', { name: 'Create token', exact: true }).click()
  const token = await page.getByRole('textbox', { name: 'New access token', exact: true }).inputValue()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await page.goto(space.url)
  await expect(page.getByRole('heading', { name: 'Push your first commit', exact: true })).toBeVisible()

  // All transport uses the URL shown in the UI, including the frontend proxy.
  // A separate Git process cannot fall back to the browser's login cookie.
  const source = join(environment.root, 'workflow-source')
  const git = (args: string[]) => environment.git(['-C', source, ...args], token)
  await environment.git(['init', '--initial-branch=master', source])
  await git(['remote', 'add', 'origin', remote])
  await mkdir(join(source, 'docs'))
  const guide = 'docs/guide #%.md'
  await writeFile(join(source, 'README.md'), '# First version\n')
  await writeFile(join(source, guide), '# Getting started\n')
  await git(['add', '.'])
  await git(['commit', '-m', 'Initial project'])
  const first = (await git(['rev-parse', 'HEAD'])).stdout.trim()
  await git(['tag', '-a', 'v1', '-m', 'First release'])
  await git(['push', '-u', 'origin', 'master', '--tags'])
  await page.getByRole('button', { name: 'Refresh files', exact: true }).click()
  await expect(page.getByLabel('Branch', { exact: true })).toHaveValue('master')
  await expect(page.getByRole('heading', { name: 'First version', exact: true })).toBeVisible()

  // The first push must repair the remote HEAD even when its branch is not main.
  const checkout = join(environment.root, 'workflow-checkout')
  const clone = await environment.git(['clone', remote, checkout], token)
  expect(clone.stderr).not.toMatch(/remote HEAD refers to nonexistent ref|unable to checkout/)
  expect((await environment.git(['-C', checkout, 'branch', '--show-current'])).stdout.trim()).toBe('master')
  expect((await environment.git(['-C', checkout, 'rev-parse', 'HEAD'])).stdout.trim()).toBe(first)
  expect(await readFile(join(checkout, 'README.md'), 'utf8')).toBe('# First version\n')
  expect(await readFile(join(checkout, guide), 'utf8')).toBe('# Getting started\n')

  await git(['switch', '-c', 'main'])
  await writeFile(join(source, 'README.md'), '# Current version\n')
  await git(['add', '.'])
  await git(['commit', '-m', 'Update project'])
  const latest = (await git(['rev-parse', 'HEAD'])).stdout.trim()
  await git(['push', '-u', 'origin', 'main'])
  await page.reload()
  await expect(page.getByRole('heading', { name: 'First version', exact: true })).toBeVisible()
  await openSettings(page)
  await page.getByLabel('Default branch', { exact: true }).selectOption('main')
  await page.getByRole('button', { name: 'Save default branch', exact: true }).click()
  await expect(page.getByText('Default branch saved.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Default branch', { exact: true })).toHaveValue('main')
  await page.getByRole('navigation', { name: 'Space navigation', exact: true }).getByRole('link', { name: 'Code', exact: true }).click()
  await expect(page.getByLabel('Branch', { exact: true })).toHaveValue('main')
  await expect(page.getByRole('heading', { name: 'Current version', exact: true })).toBeVisible()

  const currentCheckout = join(environment.root, 'workflow-current-checkout')
  const currentClone = await environment.git(['clone', remote, currentCheckout], token)
  expect(currentClone.stderr).not.toMatch(/remote HEAD refers to nonexistent ref|unable to checkout/)
  expect((await environment.git(['-C', currentCheckout, 'branch', '--show-current'])).stdout.trim()).toBe('main')
  expect((await environment.git(['-C', currentCheckout, 'rev-parse', 'HEAD'])).stdout.trim()).toBe(latest)
  expect(await readFile(join(currentCheckout, 'README.md'), 'utf8')).toBe('# Current version\n')
  await environment.git(['-C', checkout, 'fetch', 'origin'], token)
  expect((await environment.git(['-C', checkout, 'show', 'origin/main:README.md'])).stdout).toBe('# Current version\n')

  const banner = page.getByLabel('Latest commit', { exact: true })
  await expect(banner.getByRole('link', { name: 'Update project', exact: true })).toHaveAttribute('href', space.url + '/commit/' + latest)
  await banner.getByRole('link', { name: '2 commits', exact: true }).click()
  expect(new URL(page.url()).search).toBe('')
  const history = page.getByRole('region', { name: 'Commit history', exact: true })
  await expect(history).toContainText('Initial project')
  await history.getByRole('link').filter({ hasText: 'Update project' }).click()
  await expect(page).toHaveURL(environment.webOrigin + space.url + '/commit/' + latest)
  const diff = page.getByRole('region', { name: 'File diff', exact: true })
  await expect(diff).toContainText('-# First version')
  await expect(diff).toContainText('+# Current version')
  await page.reload()
  await expect(diff).toContainText('+# Current version')
  await page.getByRole('navigation', { name: 'Repository views', exact: true }).getByRole('link', { name: 'Compare', exact: true }).click()
  const comparison = page.getByRole('region', { name: 'Version comparison', exact: true })
  await comparison.getByLabel('Base', { exact: true }).selectOption('refs/tags/v1')
  await comparison.getByLabel('Target', { exact: true }).selectOption('refs/heads/main')
  await expect(diff).toContainText('-# First version')
  await expect(diff).toContainText('+# Current version')
  expect(new URL(page.url()).search).toBe('')

  await page.goto(space.url + '/tag/v1')
  await expect(page.getByRole('heading', { name: 'First version', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Clone', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Clone URL', exact: true })).toHaveValue(remote)
  const downloading = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Download ZIP', exact: true }).click()
  const download = await downloading
  const files = unzipSync(await readFile((await download.path())!))
  const prefix = `${space.slug}-${first.slice(0, 7)}/`
  expect(strFromU8(files[prefix + 'README.md']!)).toBe('# First version\n')
  expect(strFromU8(files[prefix + guide]!)).toBe('# Getting started\n')
})
