import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { GetSpace200, ListGitSpaceReferences200 } from '../src/api/generated/api.schemas.js'
import { test, expect } from './fixtures.js'
import { createSpace, register, signIn } from './helpers.js'

test('reference lists show paged commit metadata and preserve branch/tag navigation', async ({ page, environment, request }, testInfo) => {
  const user = await register(page, 'Reference owner')
  await signIn(page, user)
  const space = await createSpace(page, 'References repository')
  const base = `/api/namespaces/${space.account}/spaces/${space.slug}`
  const metadata = await (await page.request.get(base)).json() as GetSpace200
  await page.goto(space.url + '?view=refs')
  await expect(page.getByRole('heading', { name: 'No references found', exact: true })).toBeVisible()
  const work = join(environment.root, 'refs-seed')
  await environment.git(['clone', join(environment.root, 'data', metadata.id), work])
  const git = (args: string[]) => environment.git(['-C', work, ...args])
  await writeFile(join(work, 'README.md'), '# Reference release\n')
  await git(['add', '.']); await git(['commit', '-m', 'Release commit'])
  const release = (await git(['rev-parse', 'HEAD'])).stdout.trim()
  const committedAt = (await git(['show', '-s', '--format=%cI'])).stdout.trim()
  await git(['tag', '-a', 'release/首版', '-m', 'First release'])
  await git(['tag', '-a', 'nested', 'release/首版', '-m', 'Nested release'])
  // Non-commit tags are intentionally not browsable as repository versions.
  const tree = (await git(['rev-parse', 'HEAD^{tree}'])).stdout.trim()
  await git(['tag', 'tree-only', tree])
  await writeFile(join(work, 'README.md'), '# Development\n')
  await git(['add', '.']); await git(['commit', '-m', 'Development commit'])
  const current = (await git(['rev-parse', 'HEAD'])).stdout.trim()
  const topics = Array.from({ length: 31 }, (_, i) => `topic/${String(i).padStart(2, '0')}`)
  await git(['push', 'origin', 'HEAD:main', 'HEAD:refs/heads/release/首版', ...topics.map(name => 'HEAD:refs/heads/' + name), '--tags'])
  expect((await request.get(base + '/git/refs?type=branch')).status()).toBe(401)
  expect((await page.request.get(base + '/git/refs?type=invalid')).status()).toBe(400)
  expect((await page.request.get(base + '/git/refs?type=branch&limit=101')).status()).toBe(400)
  const tags = await (await page.request.get(base + '/git/refs?type=tag')).json() as ListGitSpaceReferences200
  expect(tags.total).toBe(2)
  for (const tag of tags.items) expect(tag.commit).toMatchObject({ id: release, message: 'Release commit', committedAt })
  const branches = await (await page.request.get(base + '/git/refs?type=branch&limit=2&search=TOPIC')).json() as ListGitSpaceReferences200
  expect(branches.total).toBe(31); expect(branches.hasMore).toBe(true)
  expect(branches.items.map(ref => ref.name)).toEqual(['topic/00', 'topic/01'])
  expect(branches.items[0]!.commit.id).toBe(current)
  await page.reload()
  const list = page.getByRole('region', { name: 'Reference list', exact: true })
  await expect(list.getByRole('heading', { name: 'Branches (33)', exact: true })).toBeVisible()
  await expect(list.getByText('Default', { exact: true })).toBeVisible()
  await expect(list.locator('time').first()).toHaveAttribute('datetime', /\d{4}-\d{2}-\d{2}T/)
  await list.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(list.getByText('Page 2', { exact: true })).toBeVisible()
  await expect(list.getByRole('link', { name: 'topic/30', exact: true })).toBeVisible()
  await page.reload()
  await expect(list.getByText('Page 2', { exact: true })).toBeVisible()
  await list.getByLabel('Search references', { exact: true }).fill('release/')
  await list.getByRole('button', { name: 'Search', exact: true }).click()
  await expect(list.getByRole('heading', { name: 'Branches (1)', exact: true })).toBeVisible()
  await list.getByRole('link', { name: 'release/首版', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Development', exact: true })).toBeVisible()
  await page.getByRole('navigation', { name: 'Repository views' }).getByRole('link', { name: 'References', exact: true }).click()
  await expect(list.getByRole('heading', { name: 'Branches (33)', exact: true })).toBeVisible()
  await page.getByLabel('Reference type', { exact: true }).selectOption('tag')
  await expect(list.getByRole('heading', { name: 'Tags (2)', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('reference-list.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('reference-list-mobile.png'), fullPage: true })
  await list.getByRole('link', { name: /Release commit/ }).last().click()
  await expect(page.getByRole('region', { name: 'File diff', exact: true })).toContainText('+# Reference release')
  expect(new URL(page.url()).searchParams.get('refType')).toBe('tag')
  expect(new URL(page.url()).searchParams.get('commit')).toBe(release)
  await page.getByRole('navigation', { name: 'Repository views' }).getByRole('link', { name: 'References', exact: true }).click()
  await list.getByRole('link', { name: 'release/首版', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Reference release', exact: true })).toBeVisible()
})
