import { readFile } from 'node:fs/promises'
import { test, expect } from './fixtures.js'
import { createSpace, register, signIn } from './helpers.js'
import type { Locator } from '@playwright/test'

async function playAndSeek(player: Locator) {
  await expect.poll(() => player.evaluate((element: HTMLMediaElement) => element.readyState)).toBeGreaterThanOrEqual(1)
  expect(await player.evaluate((element: HTMLMediaElement) => element.paused)).toBe(true)
  await player.evaluate(async (element: HTMLMediaElement) => { element.muted = true; await element.play() })
  await expect.poll(() => player.evaluate((element: HTMLMediaElement) => element.currentTime)).toBeGreaterThan(0.25)
  await player.evaluate((element: HTMLMediaElement) => { element.currentTime = 5 })
  await expect.poll(() => player.evaluate((element: HTMLMediaElement) => element.currentTime)).toBeGreaterThan(5.25)
  expect(await player.evaluate((element: HTMLMediaElement) => element.error)).toBeNull()
}

test('Media opens a standalone player, plays and seeks, and keeps file management separate', async ({ page: manager, browser, environment }, testInfo) => {
  test.setTimeout(120_000)
  const user = await register(manager, 'Media owner')
  await signIn(manager, user)
  const space = await createSpace(manager, 'My media', undefined, 'media')
  const base = `/api/namespaces/${space.account}/spaces/${space.slug}`
  const { id: spaceId } = await (await manager.request.get(base)).json() as { id: string }
  await expect(manager.getByRole('region', { name: 'Files', exact: true })).toBeVisible()
  await expect(manager.getByRole('region', { name: 'Media library' })).toHaveCount(0)
  const opened = manager.waitForEvent('popup')
  await manager.getByRole('link', { name: 'Open app (opens in a new tab)' }).click()
  const page = await opened
  const playerUrl = `/app/media/${spaceId}`
  await expect(page).toHaveURL(environment.webOrigin + playerUrl)
  await expect(page.getByRole('banner')).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Space details' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Upload', exact: true })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Settings', exact: true })).toHaveCount(0)
  await expect(page).toHaveTitle('My media · Media')
  await expect(page.getByRole('heading', { name: 'No media yet' })).toBeVisible()
  const source = (name: string) => readFile(new URL('./media-fixtures/' + name, import.meta.url))
  for (const [name, mimeType] of [['tone.mp3', 'audio/mpeg'], ['clip.mp4', 'video/mp4'], ['clip.webm', 'video/webm'], ['photo.png', 'image/png']] as const) {
    await manager.getByLabel('Choose a file to upload', { exact: true }).setInputFiles({ name, mimeType, buffer: await source(name) })
    await expect(manager.getByRole('status').filter({ hasText: `Uploaded ${name}.` })).toBeVisible()
  }
  expect((await page.request.put(base + '/objects/second.png', { headers: { 'content-type': 'image/png' }, data: await source('photo.png') })).status()).toBe(201)
  await page.getByRole('button', { name: 'Reload', exact: true }).click()
  const activePlayer = page.getByRole('region', { name: 'Now playing', exact: true })
  await expect(page.getByRole('navigation', { name: 'Media categories' })).toBeVisible()
  await expect(activePlayer).toHaveCount(0)
  const videoCard = page.getByRole('button', { name: 'Open media clip.mp4', exact: true })
  await expect.poll(() => videoCard.locator('video').evaluate((video: HTMLVideoElement) => video.videoWidth)).toBeGreaterThan(0)
  expect(await videoCard.locator('video').evaluate((video: HTMLVideoElement) => video.paused)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('media-grid-desktop.png'), fullPage: true, animations: 'disabled' })
  const rangeRequests: string[] = []
  page.on('response', response => {
    if (response.url().includes('/media/content') && response.status() === 206) rangeRequests.push(response.url())
  })
  await page.getByRole('button', { name: 'Open media tone.mp3', exact: true }).click()
  const audio = activePlayer.locator('audio')
  await playAndSeek(audio)
  const oldAudio = await audio.elementHandle()
  await page.getByRole('button', { name: 'Open media clip.mp4', exact: true }).click()
  expect(await oldAudio!.evaluate(element => ({ paused: (element as HTMLMediaElement).paused, src: element.getAttribute('src') }))).toEqual({ paused: true, src: null })
  await playAndSeek(activePlayer.locator('video'))
  expect(await page.evaluate(() => document.fullscreenElement)).toBeNull()
  const expanded = await activePlayer.boundingBox()
  const thumbnail = await videoCard.boundingBox()
  expect(expanded!.width).toBeGreaterThan(thumbnail!.width)
  await page.screenshot({ path: testInfo.outputPath('media-expanded-desktop.png'), fullPage: true, animations: 'disabled' })
  const closedVideo = await activePlayer.locator('video').elementHandle()
  await page.getByRole('button', { name: 'Close player', exact: true }).click()
  await expect(activePlayer).toHaveCount(0)
  expect(await closedVideo!.evaluate(element => ({ paused: (element as HTMLMediaElement).paused, src: element.getAttribute('src') }))).toEqual({ paused: true, src: null })
  await expect(videoCard).toBeFocused()
  await page.getByRole('button', { name: 'Open media clip.webm', exact: true }).click()
  await playAndSeek(activePlayer.locator('video'))
  await page.keyboard.press('Escape')
  await expect(activePlayer).toHaveCount(0)
  expect(rangeRequests.some(url => url.includes('tone.mp3'))).toBe(true)
  expect(rangeRequests.some(url => url.includes('clip.mp4'))).toBe(true)
  expect(rangeRequests.every(url => url.includes('versionId='))).toBe(true)
  await page.getByRole('button', { name: 'Reload', exact: true }).click()
  await page.getByRole('button', { name: 'Photos', exact: true }).click()
  await page.getByRole('button', { name: 'Open media photo.png', exact: true }).click()
  await expect.poll(() => page.getByRole('img', { name: 'photo.png', exact: true }).evaluate((image: HTMLImageElement) => image.naturalWidth)).toBe(320)
  await page.getByRole('button', { name: 'Next photo' }).click()
  await expect(page.getByRole('img', { name: 'second.png', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Previous photo' }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('link', { name: 'Download', exact: true }).click()
  expect((await download).suggestedFilename()).toBe('photo.png')
  await page.screenshot({ path: testInfo.outputPath('media-desktop.png'), fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('media-mobile.png'), fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.getByRole('button', { name: 'All media', exact: true }).click()
  await expect(page.getByRole('button', { name: 'All media', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await manager.getByRole('button', { name: 'Open tone.mp3', exact: true }).click()
  await manager.getByRole('dialog').getByRole('button', { name: 'Delete file', exact: true }).click()
  await manager.getByRole('button', { name: 'Confirm delete', exact: true }).click()
  await page.getByRole('button', { name: 'Reload', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open media tone.mp3', exact: true })).toHaveCount(0)
  expect((await page.request.put(base + '/objects/broken.mp3', { headers: { 'content-type': 'audio/mpeg' }, data: 'not audio' })).status()).toBe(201)
  await page.getByRole('button', { name: 'Reload', exact: true }).click()
  await page.getByRole('button', { name: 'Open media broken.mp3', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Cannot play this file')
  expect((await page.request.patch(base, { data: { visibility: 'public' } })).status()).toBe(200)
  const guestContext = await browser.newContext()
  try {
    const guest = await guestContext.newPage()
    await guest.goto(environment.webOrigin + playerUrl)
    await expect(guest.getByRole('banner')).toHaveCount(0)
    await expect(guest.getByRole('button', { name: 'Upload', exact: true })).toHaveCount(0)
    await guest.getByRole('button', { name: 'Open media clip.mp4', exact: true }).click()
    await playAndSeek(guest.getByRole('region', { name: 'Now playing' }).locator('video'))
    expect((await page.request.patch(base, { data: { visibility: 'private' } })).status()).toBe(200)
    await guest.getByRole('button', { name: 'Reload', exact: true }).click()
    await expect(guest.getByRole('heading', { name: 'Unable to load media' })).toBeVisible()
    await expect(guest.locator('video')).toHaveCount(0)
    await guest.reload()
    await expect(guest.getByRole('heading', { name: 'Sign in to open this app' })).toBeVisible()
    await guest.getByRole('link', { name: 'Sign in', exact: true }).click()
    await guest.getByLabel('Email', { exact: true }).fill(user.email)
    await guest.getByLabel('Password', { exact: true }).fill(user.password)
    await guest.getByRole('main').getByRole('button', { name: 'Sign in', exact: true }).click()
    await expect(guest).toHaveURL(environment.webOrigin + playerUrl)
    await expect(guest.getByRole('heading', { name: 'My media', exact: true })).toBeVisible()
    await expect(guest.getByRole('banner')).toHaveCount(0)
  } finally { await guestContext.close() }

  await manager.goto(`/${space.account}`)
  const card = manager.getByRole('region', { name: 'Space list' }).getByRole('link').filter({ has: manager.getByRole('heading', { name: 'My media', exact: true }) })
  await expect(card).toHaveAttribute('href', space.url)
  await expect(card).not.toHaveAttribute('target', '_blank')
  const pagesBeforeClick = manager.context().pages().length
  await card.click()
  await expect(manager).toHaveURL(environment.webOrigin + space.url)
  expect(manager.context().pages()).toHaveLength(pagesBeforeClick)
  await expect(manager.getByRole('region', { name: 'Files', exact: true })).toBeVisible()
  await expect(manager.locator('audio, video')).toHaveCount(0)
  await expect(manager.getByRole('region', { name: 'Media library' })).toHaveCount(0)
  await manager.screenshot({ path: testInfo.outputPath('media-space-desktop.png'), fullPage: true, animations: 'disabled' })
  await manager.setViewportSize({ width: 390, height: 844 })
  expect(await manager.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await manager.screenshot({ path: testInfo.outputPath('media-space-mobile.png'), fullPage: true, animations: 'disabled' })
  const appOpened = manager.waitForEvent('popup')
  await manager.getByRole('link', { name: 'Open app (opens in a new tab)' }).click()
  const appPage = await appOpened
  await expect(appPage).toHaveURL(environment.webOrigin + playerUrl)
  await expect(appPage.getByRole('heading', { name: 'My media', exact: true })).toBeVisible()
  await appPage.close()
  const plain = await manager.request.post(`/api/namespaces/${space.account}/spaces`, { data: { name: 'Plain files', slug: 'plain-files', type: 'object' } })
  expect(plain.status()).toBe(201)
  const { id: plainId } = await plain.json() as { id: string }
  await page.goto(`/app/media/${plainId}`)
  await expect(page.getByRole('heading', { name: 'App not found' })).toBeVisible()
  await page.goto('/app/media/not-a-space-id')
  await expect(page.getByRole('heading', { name: 'App not found' })).toBeVisible()
  await page.goto(`/app/unavailable/${spaceId}`)
  await expect(page.getByRole('heading', { name: 'App not available' })).toBeVisible()
  await page.close()
})
