import { test, expect } from './fixtures.js'
import { createSpace, register, signIn } from './helpers.js'

test('Note creates Markdown files, previews inline, saves versions and protects conflicting edits', async ({ page, browser, environment }, testInfo) => {
  test.setTimeout(120_000)
  const user = await register(page, 'Note owner')
  await signIn(page, user)
  const space = await createSpace(page, 'My notebook', undefined, 'note')
  const base = `/api/namespaces/${space.account}/spaces/${space.slug}`
  const { id } = await (await page.request.get(base)).json() as { id: string }
  const appPath = `/app/note/${id}`
  await page.goto(appPath)
  await expect(page.getByRole('heading', { name: 'A little room to think.' })).toBeVisible()
  await page.getByRole('button', { name: '+ New note', exact: true }).click()
  await page.getByLabel('Note name', { exact: true }).fill('Journal/Today')
  await page.getByRole('button', { name: 'Create note', exact: true }).click()
  await expect(page).toHaveURL(/\/app\/note\/[^/]+\/note\/[^/]+$/)
  const noteUrl = page.url()
  const editor = page.getByRole('textbox', { name: 'Note content', exact: true })
  await expect(editor).toBeEditable()
  const content = '# A quiet morning\n\nA **small idea** worth keeping.\n\n- Read a book\n- Take a walk\n\n[Example](https://example.com)\n\n<script>window.evil = true</script>\n\n'
  await editor.click()
  await page.keyboard.insertText(content)
  await expect(page.locator('.note-h1')).toContainText('A quiet morning')
  await expect(page.locator('.note-strong')).toContainText('small idea')
  await expect(page.locator('.cm-editor')).toHaveCount(1)
  await expect(page.locator('.cm-content script')).toHaveCount(0)
  await page.keyboard.press('ControlOrMeta+s')
  await expect(page.getByRole('status', { name: '' }).filter({ hasText: /^Saved$/ })).toBeVisible()
  let listing = await (await page.request.get(base + '/note')).json()
  const first = listing.objects[0]
  expect(first.key).toBe('Journal/Today.md')
  const rawUrl = (file: { key: string; versionId: string }) => base + '/note/content?' + new URLSearchParams({ key: file.key, versionId: file.versionId })
  expect(await (await page.request.get(rawUrl(first))).text()).toBe(content)
  await page.reload()
  await expect(editor).toContainText('small idea')
  await page.screenshot({ path: testInfo.outputPath('note-light.png'), fullPage: true })
  await page.evaluate(() => localStorage.setItem('enspatium-color-mode', 'dark'))
  await page.reload()
  await expect(editor).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('note-dark.png'), fullPage: true })
  // Plain-text MIME uploads still need a Markdown filename; unrelated text is filtered out.
  for (const key of ['Imported.md', 'Hidden.txt']) {
    expect((await page.request.put(base + '/objects/' + key, { data: '# Imported', headers: { 'content-type': 'text/plain' } })).status()).toBe(201)
  }
  listing = await (await page.request.get(base + '/note')).json()
  expect(listing.objects.map((file: { key: string }) => file.key)).toEqual(['Imported.md', 'Journal/Today.md'])
  // Another tab updates the same file while this editor retains its original precondition.
  const newer = await page.request.put(base + '/objects/' + encodeURIComponent(first.key) + '?expectedVersion=' + first.versionId, { data: '# From another tab', headers: { 'content-type': 'text/markdown' } })
  expect(newer.status()).toBe(201)
  await editor.click()
  await page.keyboard.press('ControlOrMeta+End')
  await page.keyboard.insertText('My unsaved draft')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('changed elsewhere')
  await expect(editor).toContainText('My unsaved draft')
  const current = await newer.json()
  expect(await (await page.request.get(rawUrl(current))).text()).toBe('# From another tab')
  await page.getByRole('link', { name: 'Note', exact: true }).click()
  await expect(page.getByRole('alertdialog')).toBeVisible()
  await page.getByRole('button', { name: 'Stay', exact: true }).click()
  await expect(page).toHaveURL(noteUrl)
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Reload note', exact: true }).click()
  await expect(editor).toContainText('From another tab')
  await editor.click()
  await page.keyboard.press('ControlOrMeta+End')
  await page.keyboard.insertText('\n\nMy final note')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: /^Saved$/ })).toBeVisible()
  const history = await (await page.request.get(base + '/object-versions?' + new URLSearchParams({ key: first.key }))).json()
  expect(history.versions.length).toBeGreaterThanOrEqual(2)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('note-mobile.png'), fullPage: true })
  // Private notes require login; public notes are readable but cannot be edited by guests.
  const guestContext = await browser.newContext()
  try {
    const guest = await guestContext.newPage()
    await guest.goto(noteUrl)
    await expect(guest.getByRole('heading', { name: 'Sign in to open this app' })).toBeVisible()
    expect((await page.request.patch(base, { data: { visibility: 'public' } })).status()).toBe(200)
    await guest.reload()
    await expect(guest.getByText('Read only', { exact: true })).toBeVisible()
    await expect(guest.getByRole('button', { name: 'Save', exact: true })).toHaveCount(0)
    await expect(guest.getByRole('textbox', { name: 'Note content' })).not.toBeEditable()
    expect((await guest.request.put(environment.webOrigin + base + '/objects/guest.md', { data: '# Nope', headers: { 'content-type': 'text/markdown' } })).status()).toBe(401)
    expect((await guest.request.get(environment.webOrigin + rawUrl(first))).status()).toBe(404)
  } finally { await guestContext.close() }
})
