import { test, expect } from './fixtures.js'
import { createSpace, register, signIn } from './helpers.js'

test('Note actions rename, move and soft-delete with stable links, versions and conflict checks', async ({ page, browser }, testInfo) => {
  test.setTimeout(120_000)
  const owner = await register(page, 'Notebook owner')
  await signIn(page, owner)
  const space = await createSpace(page, 'Managed notebook', undefined, 'note')
  const base = `/api/namespaces/${space.account}/spaces/${space.slug}`
  const { id } = await (await page.request.get(base)).json()
  async function upload(key: string, text: string) {
    const response = await page.request.put(base + '/objects/' + encodeURIComponent(key), { data: text, headers: { 'content-type': 'text/markdown' } })
    expect(response.status()).toBe(201)
    return response.json()
  }
  await upload('Journal/Today.md', '# First version')
  const original = await upload('Journal/Today.md', '# Second version')
  await upload('Journal/Taken.md', '# Other note')
  const appPath = `/app/note/${id}`
  const notePath = `${appPath}/note/${original.id}`
  await page.goto(notePath)
  const editor = page.getByRole('textbox', { name: 'Note content', exact: true })
  const actions = page.getByRole('button', { name: 'Note actions', exact: true })
  const dialog = page.getByRole('dialog')
  async function open(action: string) {
    await actions.click()
    await page.getByRole('menuitem', { name: action, exact: true }).click()
    await expect(dialog).toBeVisible()
  }
  await expect(editor).toBeEditable()
  await open('Rename')
  await dialog.getByLabel('Note name', { exact: true }).fill('../invalid')
  await expect(dialog.getByRole('button', { name: 'Save name' })).toBeDisabled()
  await dialog.getByLabel('Note name', { exact: true }).fill('Taken')
  await dialog.getByRole('button', { name: 'Save name' }).click()
  await expect(dialog.getByRole('alert')).toContainText('name is used')
  await dialog.getByLabel('Note name', { exact: true }).fill('Ideas')
  await dialog.getByRole('button', { name: 'Save name' }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Ideas', exact: true })).toBeVisible()
  await expect(page).toHaveURL(new RegExp(notePath + '$'))
  await expect(page.getByRole('link', { name: 'Open Journal/Ideas.md', exact: true })).toHaveAttribute('aria-current', 'page')
  await open('Move')
  await dialog.getByLabel('Destination folder', { exact: true }).fill('Archive/2026')
  await dialog.getByRole('button', { name: 'Move note', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  const key = 'Archive/2026/Ideas.md'
  await expect(page.getByRole('link', { name: `Open ${key}`, exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Open Journal/Ideas.md', exact: true })).toHaveCount(0)
  await expect(page).toHaveURL(new RegExp(notePath + '$'))
  const historyPath = base + '/object-versions?' + new URLSearchParams({ key })
  const unchanged = await (await page.request.get(historyPath)).json()
  expect(unchanged.object).toMatchObject({ id: original.id, versionId: original.versionId, revision: original.revision })
  expect(unchanged.versions).toHaveLength(2)
  // Save without reloading: the editor must use the new key and current version.
  await editor.click()
  await page.keyboard.press('ControlOrMeta+End')
  await page.keyboard.insertText('\n\nAfter moving')
  await expect(actions).toBeDisabled()
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(actions).toBeEnabled()
  const saved = await (await page.request.get(base + '/note/' + original.id)).json()
  expect(saved.key).toBe(key)
  expect(saved.versionId).not.toBe(original.versionId)
  expect(saved.revision).toBe(original.revision + 1)
  await page.reload()
  await expect(editor).toContainText('After moving')
  await page.screenshot({ path: testInfo.outputPath('note-managed.png'), fullPage: true })
  // A public reader has no management controls or mutation access.
  expect((await page.request.patch(base, { data: { visibility: 'public' } })).status()).toBe(200)
  const context = await browser.newContext({ baseURL: new URL(page.url()).origin })
  try {
    const guest = await context.newPage()
    await guest.goto(page.url())
    await expect(guest.getByText('Read only', { exact: true })).toBeVisible()
    await expect(guest.getByRole('button', { name: 'Note actions' })).toHaveCount(0)
    expect((await guest.request.delete(base + '/objects/' + encodeURIComponent(key) + '?expectedVersion=' + saved.versionId)).status()).toBe(401)
  } finally { await context.close() }
  // A stale opened version cannot rename or delete someone else's newer edit.
  const latest = await upload(key, '# A newer edit')
  await open('Rename')
  await dialog.getByLabel('Note name', { exact: true }).fill('Stale rename')
  await dialog.getByRole('button', { name: 'Save name' }).click()
  await expect(dialog.getByRole('alert')).toContainText('changed or moved elsewhere')
  await dialog.getByRole('button', { name: 'Cancel' }).click()
  await open('Delete note')
  await dialog.getByRole('button', { name: 'Confirm delete' }).click()
  await expect(dialog.getByRole('alert')).toContainText('changed or moved elsewhere')
  await dialog.getByRole('button', { name: 'Cancel' }).click()
  expect((await (await page.request.get(base + '/note/' + original.id)).json()).versionId).toBe(latest.versionId)
  await page.getByRole('button', { name: 'Reload note', exact: true }).click()
  await expect(editor).toContainText('A newer edit')
  await open('Delete note')
  await dialog.getByRole('button', { name: 'Cancel' }).click()
  await expect(editor).toBeVisible()
  await open('Delete note')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBe(0)
  await page.screenshot({ path: testInfo.outputPath('note-delete-mobile.png'), fullPage: true, animations: 'disabled' })
  await dialog.getByRole('button', { name: 'Confirm delete' }).click()
  await expect(page).toHaveURL(new RegExp(appPath + '$'))
  await expect(page.getByRole('link', { name: `Open ${key}`, exact: true })).toHaveCount(0)
  await expect(page.getByRole('alertdialog')).toHaveCount(0)
  const deleted = await (await page.request.get(historyPath)).json()
  expect(deleted.object.isDeleted).toBe(true)
  expect(deleted.versions.some((version: { versionId: string }) => version.versionId === latest.versionId)).toBe(true)
  // Existing restore machinery revives the same note URL and content.
  const restored = await page.request.post(base + '/object-versions/restore?' + new URLSearchParams({ key, versionId: latest.versionId, expectedVersion: deleted.object.versionId }))
  expect(restored.status()).toBe(201)
  await page.goto(notePath)
  await expect(editor).toContainText('A newer edit')
  await expect(page.getByRole('link', { name: `Open ${key}`, exact: true })).toBeVisible()
})
