import { test, expect } from './fixtures.js'
import { createSpace, register, signIn } from './helpers.js'

test('upload versions, preview and download history, restore, delete and recover', async ({ page }, testInfo) => {
  const user = await register(page, 'Version owner')
  await signIn(page, user)
  const space = await createSpace(page, 'Versioned files', undefined, 'object')
  await page.getByRole('link', { name: 'Settings', exact: true }).click()
  await expect(page.getByLabel('Maximum versions', { exact: true })).toHaveValue('3')
  await expect(page.getByLabel('Inactive retention (days)', { exact: true })).toHaveValue('7')
  await page.getByLabel('Maximum versions', { exact: true }).fill('5')
  await page.getByLabel('Inactive retention (days)', { exact: true }).fill('14')
  await page.getByRole('button', { name: 'Save retention', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Retention settings saved.' })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Maximum versions', { exact: true })).toHaveValue('5')
  await expect(page.getByLabel('Inactive retention (days)', { exact: true })).toHaveValue('14')
  const settings = await page.request.get(`/api/namespaces/${space.account}/spaces/${space.slug}`)
  expect(await settings.json()).toMatchObject({ objectVersionLimit: 5, objectRetentionDays: 14 })
  await page.getByRole('link', { name: 'Back to Space', exact: true }).click()
  const upload = async (contents: string) => {
    await page.getByLabel('Choose a file to upload', { exact: true }).setInputFiles({
      name: 'notes.txt', mimeType: 'text/plain', buffer: Buffer.from(contents),
    })
    await expect(page.getByRole('status')).toContainText('Uploaded notes.txt.')
  }
  await upload('First version')
  await upload('Second version')
  await page.getByRole('button', { name: 'Open notes.txt', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByLabel('File contents', { exact: true })).toHaveText('Second version')
  await dialog.getByRole('button', { name: 'Versions', exact: true }).click()
  await expect(dialog.getByText('Retention:', { exact: false })).toContainText('5 content versions; inactive versions expire after 14 days')
  await dialog.getByRole('button', { name: 'Preview version 1', exact: true }).click()
  await expect(dialog.getByLabel('File contents', { exact: true })).toHaveText('First version')
  const saved = page.waitForEvent('download')
  await dialog.getByRole('button', { name: 'Download', exact: true }).click()
  const download = await saved
  expect(download.suggestedFilename()).toBe('notes.txt')
  const stream = await download.createReadStream()
  const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
  expect(Buffer.concat(chunks).toString()).toBe('First version')
  await dialog.getByRole('button', { name: 'Restore version 1', exact: true }).click()
  await dialog.getByRole('button', { name: 'Cancel restore', exact: true }).click()
  await dialog.getByRole('button', { name: 'Restore version 1', exact: true }).click()
  await dialog.getByRole('button', { name: 'Confirm restore', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole('button', { name: 'Open notes.txt', exact: true }).click()
  await expect(dialog.getByLabel('File contents', { exact: true })).toHaveText('First version')
  await dialog.getByRole('button', { name: 'Delete file', exact: true }).click()
  await dialog.getByRole('button', { name: 'Confirm delete', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Open notes.txt', exact: true })).toHaveCount(0)
  await page.getByRole('link', { name: 'Deleted files', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Open notes.txt', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Restore version 2', exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('object-versions-mobile.png'), fullPage: true, animations: 'disabled' })
  await dialog.getByRole('button', { name: 'Restore version 2', exact: true }).click()
  await dialog.getByRole('button', { name: 'Confirm restore', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'No deleted files', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Files', exact: true }).click()
  await page.getByRole('button', { name: 'Open notes.txt', exact: true }).click()
  await expect(dialog.getByLabel('File contents', { exact: true })).toHaveText('Second version')
})
