import type { APIRequestContext } from '@playwright/test'
import { test, expect } from './fixtures.js'
import { createSpace, register, signIn } from './helpers.js'

async function upload(request: APIRequestContext, base: string, key: string, contents: string) {
  const response = await request.put(base + '/objects/' + encodeURIComponent(key), { headers: { 'content-type': 'text/plain' }, data: Buffer.from(contents) })
  expect(response.status()).toBe(201)
  return response.json()
}

test('rename and move keep IDs, versions and bytes, refresh folders, and allow historical restore', async ({ page }, testInfo) => {
  const user = await register(page, 'Move owner')
  await signIn(page, user)
  const space = await createSpace(page, 'Organized files', undefined, 'object')
  const base = `/api/namespaces/${space.account}/spaces/${space.slug}`
  await upload(page.request, base, 'notes.txt', 'First contents')
  const before = await upload(page.request, base, 'notes.txt', 'Second contents')
  const usageBefore = await (await page.request.get(base + '/storage')).json()
  await page.reload()
  await page.getByRole('checkbox', { name: 'Select notes.txt', exact: true }).check()
  await page.getByRole('button', { name: 'Open notes.txt', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('button', { name: 'Rename', exact: true }).click()
  await expect(dialog.getByLabel('Filename', { exact: true })).toHaveValue('notes.txt')
  await expect(dialog.getByRole('button', { name: 'Save name', exact: true })).toBeDisabled()
  await dialog.getByLabel('Filename', { exact: true }).fill('../invalid.txt')
  await expect(dialog.getByRole('button', { name: 'Save name', exact: true })).toBeDisabled()
  await dialog.getByLabel('Filename', { exact: true }).fill('中文 #%.txt')
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(dialog.getByLabel('File contents', { exact: true })).toHaveText('Second contents')
  await dialog.getByRole('button', { name: 'Rename', exact: true }).click()
  await dialog.getByLabel('Filename', { exact: true }).fill('中文 #%.txt')
  await page.screenshot({ path: testInfo.outputPath('rename-file.png'), animations: 'disabled' })
  await dialog.getByRole('button', { name: 'Save name', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('checkbox', { name: 'Select 中文 #%.txt', exact: true })).not.toBeChecked()
  await expect(page.getByRole('button', { name: 'Open notes.txt', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Open 中文 #%.txt', exact: true }).click()
  await dialog.getByRole('button', { name: 'Move', exact: true }).click()
  await dialog.getByLabel('Destination folder', { exact: true }).fill('books/archive/')
  await expect(dialog.getByText('New path: books/archive/中文 #%.txt', { exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('move-file-mobile.png'), animations: 'disabled' })
  await dialog.getByRole('button', { name: 'Move file', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole('link', { name: 'Open destination folder', exact: true }).click()
  await expect(page).toHaveURL(/path=books%2Farchive%2F$/)
  await page.reload()
  const key = 'books/archive/中文 #%.txt'
  await page.getByRole('button', { name: 'Open ' + key, exact: true }).click()
  await expect(dialog.getByLabel('File contents', { exact: true })).toHaveText('Second contents')
  const history = await (await page.request.get(base + '/object-versions?' + new URLSearchParams({ key }))).json()
  expect(history.object).toMatchObject({ id: before.id, versionId: before.versionId, revision: before.revision, checksumSha256: before.checksumSha256 })
  expect(history.versions).toHaveLength(2)
  expect(await (await page.request.get(base + '/storage')).json()).toEqual(usageBefore)
  await dialog.getByRole('button', { name: 'Versions', exact: true }).click()
  await dialog.getByRole('button', { name: 'Preview version 1', exact: true }).click()
  await expect(dialog.getByLabel('File contents', { exact: true })).toHaveText('First contents')
  await expect(dialog.getByRole('button', { name: 'Move', exact: true })).toBeDisabled()
  await dialog.getByRole('button', { name: 'Restore version 1', exact: true }).click()
  await dialog.getByRole('button', { name: 'Confirm restore', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole('button', { name: 'Open ' + key, exact: true }).click()
  await expect(dialog.getByLabel('File contents', { exact: true })).toHaveText('First contents')
  await dialog.getByRole('button', { name: 'Move', exact: true }).click()
  await dialog.getByLabel('Destination folder', { exact: true }).fill('')
  await dialog.getByRole('button', { name: 'Move file', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'This folder is empty', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Open destination folder', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open 中文 #%.txt', exact: true })).toBeVisible()
})

test('move rejects collisions and concurrent edits, and retries a lost response without repeating the move', async ({ page }) => {
  const user = await register(page, 'Move retry owner')
  await signIn(page, user)
  const space = await createSpace(page, 'Move conflicts', undefined, 'object')
  const base = `/api/namespaces/${space.account}/spaces/${space.slug}`
  const before = await upload(page.request, base, 'source.txt', 'Original contents')
  await upload(page.request, base, 'occupied.txt', 'Keep me')
  await page.reload()
  await page.getByRole('button', { name: 'Open source.txt', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('button', { name: 'Rename', exact: true }).click()
  await dialog.getByLabel('Filename', { exact: true }).fill('occupied.txt')
  await dialog.getByRole('button', { name: 'Save name', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('Choose another destination.')
  expect(await (await page.request.get(base + '/objects/occupied.txt')).text()).toBe('Keep me')
  await dialog.getByLabel('Filename', { exact: true }).fill('changed.txt')
  await upload(page.request, base, 'source.txt', 'Concurrent contents')
  await dialog.getByRole('button', { name: 'Save name', exact: true }).click()
  await expect(dialog.getByRole('alert')).toHaveText('This file changed or moved. Close the preview and open it again.')
  await expect(dialog.getByRole('button', { name: 'Save name', exact: true })).toBeDisabled()
  await dialog.getByRole('button', { name: 'Close preview', exact: true }).click()
  await page.getByRole('button', { name: 'Open source.txt', exact: true }).click()
  await expect(dialog.getByLabel('File contents', { exact: true })).toHaveText('Concurrent contents')
  await dialog.getByRole('button', { name: 'Rename', exact: true }).click()
  await dialog.getByLabel('Filename', { exact: true }).fill('renamed.txt')
  await page.route('**/object-move?*', async route => {
    const response = await route.fetch()
    expect(response.status()).toBe(200)
    await route.abort('failed')
  })
  await dialog.getByRole('button', { name: 'Save name', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('Unable to move')
  await page.unroute('**/object-move?*')
  await dialog.getByRole('button', { name: 'Save name', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Open renamed.txt', exact: true })).toBeVisible()
  const moved = await (await page.request.get(base + '/object-head?key=renamed.txt')).json()
  expect(moved.id).toBe(before.id)
  expect(moved.revision).toBe(2)
  const auditResponse = await page.request.get(base + '/audit-events')
  expect(auditResponse.status()).toBe(200)
  const audit = await auditResponse.json()
  expect(audit.filter((event: { action: string }) => event.action === 'object.moved')).toHaveLength(1)
})
