import { test, expect } from './fixtures.js'
import { createSpace, register, signIn } from './helpers.js'

test('browse folders, upload into the current path, preview, download and delete a file', async ({ page }, testInfo) => {
  const user = await register(page, 'Object owner')
  await signIn(page, user)
  const space = await createSpace(page, 'Object files', undefined, 'object')
  const endpoint = `/api/namespaces/${space.account}/spaces/${space.slug}/objects/`
  for (const [key, data] of [['docs/readme.txt', 'Folder contents'], ['docs/nested/deep.txt', 'Nested contents'], ['docs-other/other.txt', 'Other folder'], ['root.txt', 'Root contents']] as const) {
    expect((await page.request.put(endpoint + encodeURIComponent(key), { data, headers: { 'content-type': 'text/plain' } })).status()).toBe(201)
  }
  await page.reload()
  await expect(page.getByRole('link', { name: 'Open folder docs/', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Open root.txt', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Open docs/readme.txt', exact: true })).toHaveCount(0)
  await page.getByRole('link', { name: 'Open folder docs/', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open docs/readme.txt', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Open folder docs/nested/', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('navigation', { name: 'Folder path' }).getByRole('link', { name: 'nested', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.getByRole('button', { name: 'Open docs/nested/deep.txt', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Back to parent folder', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open docs/readme.txt', exact: true })).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('button', { name: 'Open docs/nested/deep.txt', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'New folder', exact: true }).click()
  await page.getByLabel('Folder name', { exact: true }).fill('中文 %_')
  await page.getByRole('button', { name: 'Open folder', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'This folder is empty', exact: true })).toBeVisible()
  const key = 'docs/nested/中文 %_/uploaded.txt'
  await page.getByLabel('Choose a file to upload', { exact: true }).setInputFiles({ name: 'uploaded.txt', mimeType: 'text/plain', buffer: Buffer.from('Uploaded in the nested folder') })
  await expect(page.getByRole('status').filter({ hasText: 'Uploaded uploaded.txt.' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Open ' + key, exact: true })).toBeVisible()
  expect((await page.request.get(endpoint + encodeURIComponent(key))).status()).toBe(200)
  expect((await page.request.get(endpoint + 'uploaded.txt')).status()).toBe(404)
  await page.getByRole('button', { name: 'Open ' + key, exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByLabel('File contents', { exact: true })).toHaveText('Uploaded in the nested folder')
  const downloadPromise = page.waitForEvent('download')
  await dialog.getByRole('button', { name: 'Download', exact: true }).click()
  expect((await downloadPromise).suggestedFilename()).toBe('uploaded.txt')
  await dialog.getByRole('button', { name: 'Delete file', exact: true }).click()
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Delete file', exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: 'Delete file', exact: true }).click()
  await dialog.getByRole('button', { name: 'Confirm delete', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'This folder is empty', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Back to parent folder', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Open folder docs/nested/中文 %_/', exact: true })).toHaveCount(0)
  await page.getByRole('navigation', { name: 'Folder path' }).getByRole('link', { name: 'All files', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open root.txt', exact: true })).toBeVisible()
  await page.getByLabel('Filter by filename prefix').fill('docs')
  await page.getByRole('button', { name: 'Filter', exact: true }).click()
  await expect(page).toHaveURL(/filter=docs$/)
  await expect(page.getByRole('button', { name: 'Open root.txt', exact: true })).toHaveCount(0)
  await page.getByRole('link', { name: 'Open folder docs/', exact: true }).click()
  await expect(page.getByLabel('Filter by filename prefix')).toHaveValue('')
  await page.screenshot({ path: testInfo.outputPath('object-folders.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('object-folders-mobile.png'), fullPage: true })
})
