import { test, expect } from './fixtures.js'
import { createSpace, register, signIn } from './helpers.js'

test('an Object Space allows one replaceable App with stable links and shared content', async ({ page }, testInfo) => {
  test.setTimeout(120_000)
  const duplicateKeys: string[] = []
  page.on('console', message => { if (message.text().includes('same key')) duplicateKeys.push(message.text()) })
  const user = await register(page, 'App manager')
  await signIn(page, user)
  const space = await createSpace(page, 'Shared content', undefined, 'object')
  const base = `/api/namespaces/${space.account}/spaces/${space.slug}`
  expect((await page.request.put(base + '/objects/Shared.md', { data: '# Shared words', headers: { 'content-type': 'text/markdown' } })).status()).toBe(201)
  const panel = page.getByRole('region', { name: 'Space apps' })
  await expect(panel.getByText('No apps yet.', { exact: false })).toBeVisible()
  const row = (name: string) => panel.getByRole('listitem', { name, exact: true })
  async function create(type: string, name: string) {
    await panel.getByRole('button', { name: 'New app', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: 'Create app', exact: true })
    await dialog.getByLabel('App type', { exact: true }).selectOption(type)
    await dialog.getByLabel('App name', { exact: true }).fill(name)
    await dialog.getByRole('button', { name: 'Create app', exact: true }).click()
    await expect(dialog).not.toBeVisible()
    await expect(row(name)).toBeVisible()
  }
  await create('note', 'First notebook')
  const firstHref = await row('First notebook').getByRole('link').getAttribute('href')
  await expect(panel.getByRole('button', { name: 'New app', exact: true })).toHaveCount(0)
  expect((await page.request.post(base + '/apps', { data: { appType: 'media', name: 'Extra app' } })).status()).toBe(409)
  const opened = page.waitForEvent('popup')
  await row('First notebook').getByRole('link').click()
  const openedApp = await opened
  await expect(openedApp).toHaveTitle('First notebook · Note')
  await expect(openedApp.getByRole('link', { name: 'Open Shared.md' })).toBeVisible()
  await openedApp.close()
  await row('First notebook').getByRole('button', { name: 'Rename First notebook' }).click()
  const rename = page.getByRole('dialog', { name: 'Rename app' })
  await rename.getByLabel('App name', { exact: true }).fill('Renamed notebook')
  // A failed request keeps the draft and the existing App intact.
  await page.route('**/api/namespaces/*/spaces/*/apps/*', async route => {
    if (route.request().method() === 'PATCH') await route.fulfill({ status: 500, json: { message: 'Test failure' } })
    else await route.continue()
  })
  await rename.getByRole('button', { name: 'Save name' }).click()
  await expect(rename.getByRole('alert')).toContainText('Unable to update apps')
  await expect(rename.getByLabel('App name', { exact: true })).toHaveValue('Renamed notebook')
  await page.unroute('**/api/namespaces/*/spaces/*/apps/*')
  await rename.getByRole('button', { name: 'Save name' }).click()
  await expect(rename).not.toBeVisible()
  await expect(row('Renamed notebook').getByRole('link')).toHaveAttribute('href', firstHref!)
  const renamedApp = page.waitForEvent('popup')
  await row('Renamed notebook').getByRole('link').click()
  const renamedWindow = await renamedApp
  await expect(renamedWindow).toHaveTitle('Renamed notebook · Note')
  await renamedWindow.close()

  await page.setViewportSize({ width: 390, height: 844 })
  await expect(row('Renamed notebook').getByRole('button', { name: 'Remove Renamed notebook' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('space-apps-mobile.png'), fullPage: true })
  await page.setViewportSize({ width: 1280, height: 900 })
  await row('Renamed notebook').getByRole('button', { name: 'Remove Renamed notebook' }).click()
  const removal = page.getByRole('alertdialog', { name: 'Remove app?' })
  await expect(removal).toContainText('Files, versions and permissions are kept.')
  await expect(removal.getByRole('button', { name: 'Cancel' })).toBeFocused()
  await page.screenshot({ path: testInfo.outputPath('space-app-remove.png'), animations: 'disabled' })
  await removal.getByRole('button', { name: 'Cancel' }).click()
  await expect(row('Renamed notebook')).toBeVisible()
  await row('Renamed notebook').getByRole('button', { name: 'Remove Renamed notebook' }).click()
  await removal.getByRole('button', { name: 'Remove app', exact: true }).click()
  await expect(removal).not.toBeVisible()
  await expect(row('Renamed notebook')).toHaveCount(0)
  await expect(panel.getByRole('status')).toContainText('Files and versions were kept.')
  await expect(panel.getByRole('button', { name: 'New app', exact: true })).toBeVisible()
  expect(await (await page.request.get(base + '/objects/Shared.md')).text()).toBe('# Shared words')
  await page.screenshot({ path: testInfo.outputPath('space-apps-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: 'User menu for ' + user.name, exact: true }).click()
  await page.getByRole('menuitem', { name: 'Switch to dark theme', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('menu')).not.toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await panel.getByRole('button', { name: 'New app', exact: true }).click()
  const creation = page.getByRole('dialog', { name: 'Create app', exact: true })
  await expect(creation.getByLabel('App name', { exact: true })).toHaveValue('Shared content')
  await expect(creation.getByLabel('App type', { exact: true })).toBeEnabled()
  await page.screenshot({ path: testInfo.outputPath('space-app-create-mobile-dark.png'), animations: 'disabled' })
  await creation.getByLabel('App type', { exact: true }).selectOption('media')
  await creation.getByLabel('App name', { exact: true }).fill('Photos')
  await creation.getByRole('button', { name: 'Create app', exact: true }).click()
  await expect(row('Photos')).toBeVisible()
  await expect(panel.getByRole('button', { name: 'New app', exact: true })).toHaveCount(0)
  await page.goto(firstHref!)
  await expect(page.getByRole('heading', { name: 'App not found' })).toBeVisible()
  expect(duplicateKeys).toEqual([])
})

test('public readers cannot manage Apps and a revoked owner cannot submit a stale dialog', async ({ page, browser, environment }) => {
  const user = await register(page, 'Permission manager')
  await signIn(page, user)
  const space = await createSpace(page, 'Visible notebook', undefined, 'note')
  const base = `/api/namespaces/${space.account}/spaces/${space.slug}`
  const stored = await environment.app.db.selectFrom('spaces').select(['id', 'namespace_id']).where('slug', '=', space.slug).executeTakeFirstOrThrow()
  const owner = await environment.app.db.selectFrom('users').select('id').where('email', '=', user.email).executeTakeFirstOrThrow()
  await environment.app.db.updateTable('spaces').set({ visibility: 'public' }).where('id', '=', stored.id).execute()
  const guestContext = await browser.newContext()
  try {
    const guest = await guestContext.newPage()
    await guest.goto(environment.webOrigin + space.url)
    const guestPanel = guest.getByRole('region', { name: 'Space apps' })
    await expect(guestPanel.getByRole('link', { name: 'Open Visible notebook (opens in a new tab)' })).toBeVisible()
    await expect(guestPanel.getByRole('button')).toHaveCount(0)
    expect((await guest.request.post(environment.webOrigin + base + '/apps', { data: { appType: 'note' } })).status()).toBe(401)
  } finally { await guestContext.close() }

  const panel = page.getByRole('region', { name: 'Space apps' })
  await panel.getByRole('button', { name: 'Rename Visible notebook' }).click()
  const dialog = page.getByRole('dialog', { name: 'Rename app' })
  await dialog.getByLabel('App name', { exact: true }).fill('Should not be saved')
  await environment.app.db.updateTable('namespace_members').set({ role: 'member' }).where('namespace_id', '=', stored.namespace_id).where('user_id', '=', owner.id).execute()
  await environment.app.db.updateTable('space_members').set({ role: 'writer' }).where('space_id', '=', stored.id).where('user_id', '=', owner.id).execute()
  await dialog.getByRole('button', { name: 'Save name' }).click()
  await expect(dialog).not.toBeVisible()
  await expect(panel.getByRole('alert')).toContainText('Only a Space owner can manage apps')
  await expect(panel.getByRole('button', { name: 'New app' })).toHaveCount(0)
  await expect(panel.getByRole('button', { name: 'Remove Visible notebook' })).toHaveCount(0)
  await expect(panel.getByRole('listitem', { name: 'Visible notebook', exact: true })).toBeVisible()
  expect((await page.request.patch(base + `/apps/${stored.id}`, { data: { name: 'Forbidden' } })).status()).toBe(403)
  await environment.app.db.updateTable('space_members').set({ role: 'reader' }).where('space_id', '=', stored.id).where('user_id', '=', owner.id).execute()
  await page.reload()
  await expect(panel.getByRole('link')).toBeVisible()
  await expect(panel.getByRole('button')).toHaveCount(0)
})
