import { test, expect } from './fixtures.js'
import { register, signIn, signOut } from './helpers.js'

test('user settings save a profile and manage tokens under Applications', async ({ page, request }, testInfo) => {
  expect((await request.patch('/api/auth/me', { data: { displayName: 'Anonymous' } })).status()).toBe(401)
  const user = await register(page, 'Settings owner')
  await signIn(page, user)
  const accountUrl = page.url()
  await page.getByRole('button', { name: 'User menu for ' + user.name, exact: true }).click()
  await expect(page.getByRole('menuitem', { name: 'Access tokens', exact: true })).toHaveCount(0)
  await page.getByRole('menuitem', { name: 'Settings', exact: true }).click()
  await expect(page).toHaveURL(/\/settings\/profile$/)
  const nav = page.getByRole('navigation', { name: 'Settings navigation' })
  await expect(nav.getByRole('link', { name: 'Personal profile', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.getByLabel('Email', { exact: true })).toHaveValue(user.email)
  expect((await page.request.patch('/api/auth/me', { data: { displayName: '   ' } })).status()).toBe(400)
  await page.getByLabel('Display name', { exact: true }).fill('Updated owner')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Profile saved.')
  user.name = 'Updated owner'
  await expect(page.getByRole('button', { name: 'User menu for ' + user.name, exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Display name', { exact: true })).toHaveValue(user.name)
  await page.screenshot({ path: testInfo.outputPath('profile-settings.png'), fullPage: true })
  await page.getByRole('link', { name: 'View profile', exact: true }).click()
  await expect(page).toHaveURL(accountUrl)
  await expect(page.getByRole('heading', { name: user.name, exact: true })).toBeVisible()
  await page.goto('/settings/applications')
  await expect(nav.getByRole('link', { name: 'Applications', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.getByLabel('Name', { exact: true }).fill('Settings test token')
  await page.getByRole('button', { name: 'Create token', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Your token is ready', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Copy access token', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(page.getByLabel('New access token', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Revoke Settings test token', exact: true }).click()
  await page.getByRole('button', { name: 'Revoke token', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Token revoked.')
  await page.goto('/settings/access-tokens')
  await expect(page).toHaveURL(/\/settings\/applications$/)
  await expect(page.getByText('Revoked', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('applications-settings.png'), fullPage: true })
  await page.getByRole('button', { name: 'User menu for ' + user.name, exact: true }).click()
  await page.getByRole('menuitem', { name: 'Switch to dark theme', exact: true }).click()
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo(0, 0))
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('settings-mobile-dark.png'), fullPage: true })
  await signOut(page, user)
  await page.goto('/settings/applications')
  await expect(page).toHaveURL(/\/login$/)
  await page.getByLabel('Email', { exact: true }).fill(user.email)
  await page.getByLabel('Password', { exact: true }).fill(user.password)
  await page.getByRole('main').getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page).toHaveURL(/\/settings\/applications$/)
  await expect(page.getByRole('heading', { name: 'Applications', exact: true })).toBeVisible()
})
